PingCAP-QE/ee-ops

- apps/prod/bazel-remote/config.yaml
- apps/prod/bazel-remote/release.yaml
- apps/prod/bazel-remote/release/release.yaml
before rename or move, we should disable garbage collection.
Ref: fluxcd [faq](https://fluxcd.io/flux/faq/#how-can-i-safely-move-resources-from-one-dir-to-another)
> fix(apps/prod/bazel-remote): add label to service monitor resource

- apps/prod/jenkins/post/tidb/namespace.yaml
why: current rook-ceph fs plugin daemonset not automatic deploy pod on nodes which owned label `enable-ci=true`
> fix(apps/prod/jenkins): fix jenkins-tidb namespace's annotations

- apps/prod/bazel-remote/pre/obc.yaml
- apps/prod/jenkins/post/_base/cronjob-go-caches.yaml
- apps/prod/jenkins/post/_base/pvc.yaml
- s3 bucket size for bazel remote cache 2.5T to 5T
- gocache pvc from 500GB to 600GB
> chore(apps/prod): increase cache pvc and obc size

- apps/staging/greenhouse/kustomization.yaml
- apps/staging/greenhouse/release.yaml
- apps/staging/kustomization.yaml
- charts/greenhouse/.helmignore
- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/NOTES.txt
- charts/greenhouse/templates/_helpers.tpl
- charts/greenhouse/templates/deployment.yaml
- charts/greenhouse/templates/hpa.yaml
- charts/greenhouse/templates/ingress.yaml
- charts/greenhouse/templates/pvc.yaml
- charts/greenhouse/templates/service.yaml
- charts/greenhouse/templates/serviceaccount.yaml
- charts/greenhouse/templates/servicemonitor.yaml
- charts/greenhouse/templates/tests/test-connection.yaml
- charts/greenhouse/values.yaml
try to replace bazel remtoe cache server with [greenhouse](https://github.com/kubernetes/test-infra/tree/master/greenhouse)
TODO: upstream greenhouse image is too old, we need to build it with latest code.
My works:
> feat(charts/greenhouse,apps/staging): test for `greenhouse` in staging

- apps/prod/ats/config-override/records.config
- apps/prod/ats/release.yaml
pod limit from 48GiB to 72GiB
ram cache size from 32Gib to 64GiB
> feat(apps/prod/ats): increase ats memory limit

- apps/prod/greenhouse/release.yaml
before: using ceph-block, read speed is 120MB/s tested with rsync
> feat(apps/prod/greenhouse): use local path volume

- apps/staging/jenkins/release/values-controller-plugins.yaml
current bfa failure metric does not have jobname dimension
- built a new bfa plugin
- add prometheus relabel rule
Signed-off-by: lijie <lijie@pingcap.com>
> feat: add bfa jobname metric

- apps/staging/jenkins/release/values-JCasC.yaml
unauthenticated will be limit to 60/hour.
> feat(apps/staging/jenkins): perfer to git url to avoid github api rate limit

- apps/prod/jenkins/release/values-JCasC.yaml
from goproxy.pingcap.net to goproxy.apps.svc
> feat(apps/prod/jenkins/release): switch first go proxy to cluster service

- apps/prod/greenhouse/release.yaml
Why:
when device usage got by `df` was 99%, but cap - used was greater than 5%, greenhouse will not evict the contents.
> fix(apps/prod/greenhouse): fix evicting args for local path device mount

- apps/prod/goproxy/deployment.yaml
use https://goproxy.io instead of https://proxy.golang.org
> fix(apps/prod/goproxy): adjust upstream goproxy

- apps/prod/greenhouse/release.yaml
migrate from disk to pvc to avoid size limit in single host.
> feat(apps/prod/greenhouse): increase block pvc size to 4T

- apps/prod/jenkins/release/values-agent.yaml
current max is over 100, but cluster usage is 30%
> feat(apps/prod/jenkins/release): increase agent cap from 150 to 200

- apps/prod/goproxy/deployment.yaml
Upsteam goproxy.io causes a checksum error, adjust to use proxy.golang.org
> fix(apps/prod/goproxy): adjust upstream to proxy.golang.org

- apps/prod/jenkins/release/values-controller-plugins.yaml
- apps/staging/jenkins/release/values-controller-plugins.yaml
Add plugin timestamper to adds timestamps to the console output of Jenkins jobs for more user-friendly issue targeting.
Example
```shell
21:51:15  Started by user anonymous
21:51:15  Building on master
21:51:17  Finished: SUCCESS
```
> feat(staging/apps/jenkins): add jenkins plugin timestamper

- apps/staging/jenkins/release/values-controller-plugins.yaml
Add plugin timestamper to adds timestamps to the console output of Jenkins jobs for more user-friendly issue targeting.
Example
```shell
21:51:15  Started by user anonymous
21:51:15  Building on master
21:51:17  Finished: SUCCESS
```
> feat(staging/apps/jenkins): add plugin timestamper v1.21

- apps/staging/jenkins/release/values-controller-plugins.yaml
Related to https://github.com/jenkinsci/kubernetes-plugin/pull/1291.
Upgrade plugin kubernetes version to fix compatibility with Kubernetes client 6.x.
Error message
```shell
2023-01-10 15:49:01 |  hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: No httpclient implementations found on the context classloader, please ensure your classpath includes an implementation jar
2023-01-10 15:49:01 |  	at io.fabric8.kubernetes.client.utils.HttpClientUtils.getHttpClientFactory(HttpClientUtils.java:164)
2023-01-10 15:49:01 |  	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:145)
2023-01-10 15:49:01 |  	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:56)
2023-01-10 15:49:01 | …
```
> fix(staging/apps/jenkins): upgrade plugin kubernetes version to fix client error

- apps/prod/jenkins/post/tidb/files/bazel-prepare-in-container.sh
min between cpu cores and `total_bazel_mem_resource * 2 / default max memory per bazel task`
> feat(apps/prod/jenkins/post/tidb): optimize the bazel `--jobs` option

- apps/dev/prow/release/release.yaml
> chore(apps/dev/prow): bump hook images to `v20230303-8e409833dd-dirty`

- apps/dev/prow/release/release.yaml
> Revert "chore(apps/dev/prow): bump hook images to `v20230303-8e409833dd-dirty`"

- apps/staging/tekton/setup/operator-config.yaml
> fix(apps/staging/tekton/setup): fix tekton config field `spec.pipeline.default-timeout-minutes`

- apps/staging/tekton/setup/kustomization.yaml
current min kubernetes version need `1.24.0`
> fix(apps/staging/tekton/setup): rollback tekton operator to `v0.65.1`

- apps/_crds/prow/kustomization.yaml
- apps/dev/kustomization.yaml
- apps/dev/prow-crd.yaml
- apps/dev/prow/release/release.yaml
- apps/staging/kustomization.yaml
- apps/staging/prow-crd.yaml
- apps/staging/prow/release/release.yaml
if we do not change it, it can only deploy one helm release in a cluster.
> refactor(apps/dev,apps/staging): upgrade prow to standalone mode

- apps/gcp/prow/release/release.yaml
why: avoid dupplicate reprots with crier component.
> chore(apps/gcp/prow/release): update deployment for jenkins operator to skip report

- apps/gcp/prow/release/release.yaml
It will only update configmap, will not affect the pods.
> chore(apps/gcp/prow/release): bump prow release to v0.8.1

- apps/staging/buildfarm/configs/config.yaml
- apps/staging/buildfarm/kustomization.yaml
- apps/staging/buildfarm/redis-cluster.yaml
- apps/staging/buildfarm/server.yaml
- apps/staging/buildfarm/shard-worker.yaml
- apps/staging/kustomization.yaml
May be we should call it "local test", currently we foucs on tidb with bazel toolchain.
usage: bazel build --remote_executor=grpc://buildfarm-server.apps.svc:8980 //pkg
> feat(apps/staging): add buildfarm app to research dev-test

- apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-prowjob.yaml
- apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
should using quato to wrap the param subtitue
> fix(apps/staing/prow/post/configs/jobs): fix tekton job `codescan-security`

- apps/staging/buildfarm/server.yaml
- apps/staging/buildfarm/shard-worker.yaml
Changes: 
- fix service ports about dup name issues.
- scale for workers to make the deployment as shard mode.
> fix(apps/staging/buildfarm): fix services ports and increase replicas for workers

- apps/staging/buildfarm/configs/config.yaml
- apps/staging/buildfarm/redis-cluster.yaml
- apps/staging/buildfarm/server.yaml
- apps/staging/buildfarm/shard-worker.yaml
1. rename redis service name
2. increase resource for shard workers
1. no need to add `service` suffix to service name since it's type is `Service`.
2. it will failed with OOM killing when build heavy targets.
> chore(apps/staging/buildfarm): increase cpu and memory resource for shard workers

- apps/staging/prow/release/release.yaml
The new image solved the large message limit  of open AI server.
> fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-1216aa4`

- apps/staging/prow/release/release.yaml
The new image solved the large message limits of open AI server.
> fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-97a0d53`

- apps/staging/prow/release/release.yaml
> fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-15ca628`

- apps/staging/prow/release/release.yaml
> fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-0058871`

- apps/staging/prow/release/release.yaml
> fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-565d3ec`

- apps/dev/prow/release/release.yaml
- apps/gcp/prow/release/release.yaml
It will fix the issue of triage plugin: add `need-cherry-pick-to-*` label on PR for version not in maintain list when affect-x.y label exists.
> fix(gcp/prow/release): bump image ticommunityinfra/tichi-issue-triage-plugin to `v2.4.3`

- apps/prod/buildbarn/release.yaml
Reverts PingCAP-QE/ee-ops#570
It take no effects:
```log
2023/06/03 09:00:47 Downloading https://releases.bazel.build/5.3.2/release/bazel-5.3.2-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1419b813-6b69-4847-b9e6-5843aebd0f09
INFO: Reading 'startup' options from /apps/tidb/.bazelrc: --host_jvm_args=-Xmx5g, --unlimit_coredumps
INFO: Options provided by the client:
Inherited 'common' options: --isatty=1 --terminal_columns=96
INFO: Reading rc options for 'build' from /apps/tidb/.bazelrc:
'build' options: --announce_rc --experimental_guard_against_concurrent_changes --experimental_remote_merkle_tree_cache --java_language_version=17 --java_runtime_version=17 --tool_java_language_version=17 …
```
> Revert "Revert "Revert "chore(apps/prod/buildbarn): disable head method"""

- apps/gcp/prow/release/release.yaml
> Revert "chore(apps/prod/prow/release): bump hook image to `ticommunityinfra/hook:v20230608-bd4b41b`"

- apps/gcp/prow/release/release.yaml
it's introduced by revert commits.
> fix(apps/gcp/prow/release): fix wrong cli options of chatgpt plugin

- apps/dev/prow/release/release.yaml
> feature(apps/dev/prow/prow/release): bump hook's image tag to `v20230627-6c92121`

- apps/gcp/prow/release/release.yaml
Changes:
- https://github.com/kubernetes/test-infra/pull/29762
- https://github.com/kubernetes/test-infra/pull/29970
- other changes from upstream.
> fix(apps/gc/prow/release): bump hook image tag to `v20230629-a95a424`

- apps/gcp/prow/release/release.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2186
> fix(apps/gc/prow/release): bump image of jenkins-operator to `v20230630-a19314f`

- apps/gcp/prow/release/release.yaml
`tidb-binlog` team has not enough people on code reviewing for new commits when the PR has LGTMed.
They want make it sticked on lgtm label.
> chore(apps/gc/prow/release): add lgtm sticky repo `pingcap/tidb-binlog`

- apps/prod/prow-worker/gencred.sh
- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/operator-release.yaml
> fix(apps/prod/tekton/setup): fix the issue arm64 image for prune

- apps/prod/ccache-pvc/base/kustomization.yaml
- apps/prod/ccache-pvc/base/pvc.yaml
- apps/prod/ccache-pvc/kustomization.yaml
- apps/prod/ccache-pvc/platforms/linux-amd64/kustomization.yaml
- apps/prod/ccache-pvc/platforms/linux-arm64/kustomization.yaml
- apps/prod/kustomization.yaml
- tiflash ccache need pvc to share cache
- rust-toolchain and cargo can be cached
- add kustomization
- tested in https://cd.pingcap.net/blue/organizations/jenkins/debug%2Fbuild-tiflash/detail/build-tiflash/79/pipeline/241
> feat: add ccache pvc

- apps/prod/kustomization.yaml
> feat(apps/prod): add jenkins-beta

- apps/prod/jenkins-beta/release/namespace-agent.yaml
- apps/prod/jenkins-beta/release/values-agent.yaml
> fix(apps/prod/jenkins-beta): correct nodeselector conf

- apps/gcp/prow/release/release.yaml
> fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`

- apps/gcp/prow/release/release.yaml
> Revert "fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`"

- apps/dev/prow/release/release.yaml
> fix(apps/dev/prow/release): bump hook image to `v20230808-5546ede`

- apps/prod/tibuild/deployment.yaml
Why:
- update tibuild to fix gitRef regex
> fix: tibuild support dot in branch name

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/tests/jenkins-test.yaml
The `1.2.0` has no arm64 container image published, and the `1.10.0` has multi-arch image published.
> fix(charts/jenkins/templates/test): bump image `bats/bats` to `v1.10.0`

- apps/prod/tekton/configs/pipelines/pipeline1.yaml
- apps/prod/tekton/configs/triggers/templates/demo.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/demo.yaml
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
> chore(apps/prod/tekton/config): rename tekton resources

- apps/prod/jenkins/pre/cronjobs.yaml
- apps/staging/jenkins/pre/obc/cronjobs.yaml
deno only support x86 on linux
> fix(apps/prod/jenkins/pre): fix cronjob with deno image

- apps/prod/buildbarn/release.yaml
> fix(apps/prod/buildbarn): avoid scheduler pod on arm64 nodes

- apps/dev/prow/release/release.yaml
> fix(apps/dev/prow/release): recude resources usage

- apps/dev/prow/release/release.yaml
> chore(apps/dev/prow/release): bump image for hook to `v20230912-1e90cdf6eb`

- apps/gcp/prow/release/release.yaml
To support only inherit reviewers from parent OWNERS.
> chore(apps/gcp/prow/release): bump image for hook to `v20230912-1e90cdf6eb`

- apps/gcp/prow/release/release.yaml
> chore(apps/gcp/prow/release): bump image for hook to `v20230922-c60c561dfe`

- apps/dev/prow/release/release.yaml
lazy match default regex for full config type OWNERS files
> chore(apps/dev/prow/release): bump image for hook to `v20230927-01102e9c12`

- apps/gcp/prow/release/release.yaml
> chore(apps/gcp/prow/release): bump image for hook to `v20230927-01102e9c12`

- apps/prod/jenkins-beta/release/values-controller-plugins.yaml
- apps/prod/jenkins-beta/release/values-controller.yaml
1. Use office jenkins image rather than self build images.
1. I tested the plugins cli options and solved the issue with setting the install latest plugin option to `false`.
> fix(apps/prod/jenkins-beta/release): use office image but not install latest version plugins

- apps/prod/jenkins-beta/release/values-agent.yaml
- apps/prod/jenkins-beta/release/values-controller-plugins.yaml
- apps/prod/jenkins-beta/release/values-controller.yaml
> fix(apps/prod/jenkins-beta): bump jenkins version and plugins

- apps/prod/jenkins-beta/release/values-controller-plugins.yaml
git plugin is the downstream plugin, it no need to declare it in plugin configuration.
> fix(apps/prod/jenkins-beta/release): fix plugin

- apps/prod/jenkins-beta/release/values-controller.yaml
- apps/prod/jenkins/release/values-JCasC.yaml
- apps/prod/jenkins/release/values-agent.yaml
- apps/prod/jenkins/release/values-controller-plugins.yaml
- apps/prod/jenkins/release/values-controller.yaml
> fix(apps/prod/jenkins/release): bump jenkins controller and plugins

- apps/gcp/prow-crd.yaml
The validation of tekton pipeline spec is wrong, and is not fixed in prow upstream.
but here has a fixed version: https://github.com/kyma-project/test-infra/raw/main/prow/cluster/components/prowjob_customresourcedefinition.yaml
> fix(apps/gcp): fix prowjob crd

- apps/prod/tekton/configs/triggers/bindings/github-branch-create.yaml
- apps/prod/tekton/configs/triggers/bindings/github-branch-push.yaml
- apps/prod/tekton/configs/triggers/bindings/github-pr.yaml
- apps/prod/tekton/configs/triggers/bindings/github-tag-create.yaml
- apps/prod/tekton/configs/triggers/bindings/kustomization.yaml
- apps/prod/tekton/configs/triggers/event-listeners/event-listener.yaml
- apps/prod/tekton/configs/triggers/templates/branch-create-pingcap-qe-artifacts.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/templates/push-pingcap-qe-artifacts.yaml
- apps/prod/tekton/configs/triggers/templates/tag-create-pingcap-qe-artifacts.yaml
- apps/prod/tekton/configs/triggers/triggers/create-branch-pingcap-qe-artifacts.yaml
- apps/prod/tekton/configs/triggers/triggers/create-tag-pingcap-qe-artifacts.yaml
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/push-pingcap-qe-artifacts.yaml
- branch pushing.
- branch creating.
- tag creating.
> feat(apps/prod/tekton/config/triggers): add triggers for `pingcap-qe/artifacts`

- apps/prod/tekton/configs/tasks/create-pr-to-sync-owners.yaml
- apps/prod/tekton/configs/tasks/kustomization.yaml
- apps/prod/tekton/configs/triggers/bindings/github-branch-create.yaml
- apps/prod/tekton/configs/triggers/bindings/github-branch-push.yaml
- apps/prod/tekton/configs/triggers/bindings/github-tag-create.yaml
- apps/prod/tekton/configs/triggers/templates/branch-create-product-components-hotfix.yaml
- apps/prod/tekton/configs/triggers/triggers/create-branch-product-components-hotfix.yaml
Automatically create pull requests when hot fix branch is created:
1. Setup the Tekton triggers and tasks to watch the repositories on branch creating events.
2. Call the Deno script to create pull request to the target branch if the matched branch is created.
> feat(apps/prod/tekton/configs): add task and triggers for auto sync OWNERS for hotfix branches

- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/operator-release.yaml
it bump the pipeline component from `v0.34.1` to `v0.35.0`.
> feat(apps/prod/tekton/setup): bump tekton-operator to v0.57.0

- apps/prod/tekton/setup/operator-release.yaml
it bump the dashboard component from `v0.25.0` to `v0.26.0`.
> feat(apps/prod/tekton/setup): bump tekton-operator to v0.58.0

- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/operator-release.yaml
it bump the pipeline component from `v0.35.1` to `v0.36.0`.
Ref:
- https://github.com/tektoncd/pipeline/releases/tag/v0.36.0
> feat(apps/prod/tekton/setup): bump tekton-operator to v0.59.0

- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/operator-release.yaml
It bump these components:
- hub: [v1.8.0](https://github.com/tektoncd/hub/releases/tag/v1.8.0)
- dashboard: [v0.27.0](https://github.com/tektoncd/dashboard/releases/tag/v0.27.0)
- pipeline: [v0.37.0](https://github.com/tektoncd/pipeline/releases/tag/v0.37.0)
- chains: [v0.9.0](https://github.com/tektoncd/chains/releases/tag/v0.9.0)
> feat(apps/prod/tekton/setup): bump tekton-operator to v0.60.0

- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/operator-release.yaml
It bump these components:
- pipeline: [v0.37.2](https://github.com/tektoncd/pipeline/releases/tag/v0.37.2)
- triggers: [v0.20.2](https://github.com/tektoncd/triggers/releases/tag/v0.20.2)
> feat(apps/prod/tekton/setup): bump tekton-operator to v0.60.1

- apps/prod/tekton/configs/pipelines/push-build-package.yaml
- apps/prod/tekton/configs/tasks/git-clone.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tidb/push.yaml
- apps/prod/tekton/configs/triggers/test.http
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- also disable the passed triggers for repo: pd, tidb, tiflow
> fix(apps/prod/tekton/configs): fix git clone steps

- apps/prod/tekton/configs/pipelines/push-build-package.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/push.yaml
- apps/prod/tekton/configs/triggers/templates/tikv/tikv/push.yaml
The new builder images is WIP, now we use the old ones.
> fix(apps/prod/tekton/configs): fix builder images for tikv and tiflash building

- apps/prod/tibuild/deployment.yaml
Why:
- support pass env/builder/productImage
> feat: support env/builder/image

- apps/prod/jenkins/post/_base/cronjob-go-caches.yaml
Close https://github.com/PingCAP-QE/ee-ops/issues/778
Add node affinity on cronjob clean-go-caches.
> fix(apps/proc/jenkins): add node affinity

- apps/prod/boskos/README.md
- apps/prod/boskos/base/cleaner/deployment.yaml
- apps/prod/boskos/base/cleaner/kustomization.yaml
- apps/prod/boskos/base/cleaner/rbac.yaml
- apps/prod/boskos/base/crd.yaml
- apps/prod/boskos/base/deployment.yaml
- apps/prod/boskos/base/janitor/README.md
- apps/prod/boskos/base/janitor/deployment.yaml
- apps/prod/boskos/base/janitor/kustomization.yaml
- apps/prod/boskos/base/janitor/serviceaccount.yaml
- apps/prod/boskos/base/kustomization.yaml
- apps/prod/boskos/base/rbac.yaml
- apps/prod/boskos/base/reaper/README.md
- apps/prod/boskos/base/reaper/deployment.yaml
- apps/prod/boskos/base/reaper/kustomization.yaml
- apps/prod/boskos/base/service.yaml
- apps/prod/boskos/boskos-resources.yaml
- apps/prod/boskos/kustomization.yaml
- apps/prod/boskos/overlays/mac-machine-janitor/kustomization.yaml
- apps/prod/boskos/overlays/mac-machine-reaper/kustomization.yaml
- apps/prod/kustomization.yaml
New deployments
===
1. Deploy k8s-sig's boskos to setup the resource manager for mac machines resoures, in future, it can manage more types.
> feat(apps/prod): add boskos to support acquire and release mac builder resources

- apps/prod/tekton/setup/operator-release.yaml
With components updated:
- hub "v1.9.0"
- dashboard "v0.28.0"
- pipeline "v0.39.0"
- chains "v0.11.0"
> chore(apps/prod/tekton/setup): bump tekton operator to v0.61.0

- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
just push manifest when more than on arch tags found.
> fix(apps/prod/tekton/configs/tagsk): fix task `multi-arch-image-collect`

- charts/git-cdn/.helmignore
- charts/git-cdn/Chart.yaml
- charts/git-cdn/templates/NOTES.txt
- charts/git-cdn/templates/_helpers.tpl
- charts/git-cdn/templates/deployment.yaml
- charts/git-cdn/templates/hpa.yaml
- charts/git-cdn/templates/ingress.yaml
- charts/git-cdn/templates/service.yaml
- charts/git-cdn/templates/serviceaccount.yaml
- charts/git-cdn/templates/tests/test-connection.yaml
- charts/git-cdn/values.yaml
We will deploy it to proxy git clone globally to save CI/CD time and brandwidth.
It's based open source project [git_cdn](https://gitlab.com/grouperenault/git_cdn).
> feat(charts): add chart `git-cdn`

- .gitignore
- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tidb/build.yaml
git url instead is configurated in `.gitconfig` file of the secret.
> feature(apps/prod/tekton/configs): git clone with git-cdn

- apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/build.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tidb/build.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/build.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/build.yaml
- apps/prod/tekton/configs/triggers/templates/tikv/pd/build.yaml
- apps/prod/tekton/configs/triggers/templates/tikv/tikv/build.yaml
enable:
- pingcap/advanced-statefulset
- pingcap/tiflash
- pingcap/tiflow
- tikv/tikv
- tikv/pd
> feature(apps/prod/tekton/configs): git clone with git-cdn service

- apps/prod/tekton/setup/operator-config.yaml
Notice: currently we need update the config map `tekton-pipelines/feature-flags` manually because of the operator not support the congfiguration before v0.63.0.
> feat(apps/prod/tekton/setup): enable cloudevent emit and add sink url

- apps/prod/cloudevents-server/release.yaml
The updating will introduce the tekton event sinker feature:
sinks the cloud events of task run and pipeline run: send the state by Lark bot app.
> feat(apps/prod/cloudevents-server): bump image tag to `e652158`

- apps/prod/tibuild/deployment.yaml
and change repo to `ghcr.io/pingcap-qe/ee-apps/tibuild`.
It's built automatically.
> feat(apps/prod/tibuild): bump image tag to `2f9d4cd`

- apps/prod/kustomization.yaml
It's wrong in #461: not enable in top kustomization.yaml file
> fix(apps/prod/tibuild): add `tibuild` in kustomization.yaml

- apps/prod/tekton/setup/operator-release.yaml
With components updated:
- hub "v1.10.0"
- dashboard "v0.29.2"
- pipeline "v0.40.0"
- chains "v0.12.0"
- triggers "v0.21.0"
> chore(apps/prod/tekton/setup): bump tekton operator to v0.62.0

- apps/prod/tekton/setup/operator-release.yaml
With components updated:
- hub "v1.11.1"
- dashboard "v0.30.0"
- pipeline "v0.41.0"
- chains "v0.13.0"
- triggers "v0.22.0"
> chore(apps/prod/tekton/setup): bump tekton operator to v0.63.0

- apps/prod/tekton/setup/operator-release.yaml
With components updated:
- dashboard "v0.31.0"
- pipeline "v0.42.0"
- chains "v0.14.0"
> chore(apps/prod/tekton/setup): bump tekton operator to v0.64.0

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
let it acquire resource after checkouted source codes to reduce the resource leasing time.
> fix(apps/prod/tekton/configs/pipeline): fix task order for `pingcap-build-package-darwin`

- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
Example error:
```
[build]     Updating git repository `https://github.com/tabokie/fs2-rs`
[build]     Updating git repository `https://github.com/pingcap/rust-protobuf`
[build]     Updating git submodule `https://github.com/google/protobuf`
[build] error: failed to load source for dependency `protobuf`
[build]
[build] Caused by:
[build]   Unable to update https://github.com/pingcap/rust-protobuf?branch=v2.8#6642ebaa
[build]
[build] Caused by:
[build]   failed to update submodule `google-protobuf`
[build]
[build] Caused by:
[build]   failed to fetch submodule `google-protobuf` from https://github.com/google/protobuf
[build]
[build] Caused by:
[build]   network failure seems to have happened
[build]   if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
[build] …
```
> opt(apps/prod/tekton/configs/tasks): add env var in build step to avoid cargo fetch error

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
We put the release step in the final tasks, but currently when pipelinerun timeout, the final task will not run. It will cause the resource not be released and blocking the future runs.
> fix(apps/prod/tekton/configs/pipelines): decrease wait time and retry times for require mac resource

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
currently tiflow has wrong file links in v6.5.x' codes.
> opt(apps/prod/tekton/configs/tasks): ignore error when scp

- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
oras repo tags image:tag will hang when the tag list is too long.
> fix(apps/prod/tekton/configs/tasks): fix task `multi-arch-image-collect`

- apps/prod/tekton/configs/triggers/tests/test.http
- apps/prod/tekton/configs/triggers/triggers/_/artifact-push-on-harbor.yaml
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-push.yaml
- tidb-tools will not release from release-x.y branches.
> feat(apps/prod/tekton/configs/triggers): add triggers for `tidb-binlog` and `tidb-tools`

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
Tekton will send the failure notify for every retry, so it bothers us.
> refactor(apps/prod/tekton/configs/pipelines): increase acquire timeout rather than retry again

- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-push.yaml
the branch reversion should use `origin/master` rather than `master`
> fix(apps/prod/tekton/configs/triggers): fix trigger for `monitoring` component

- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-push.yaml
This reverts commit e446c3ad0c841b119c937bb80eac1659721e9d9e.
Lack of reproducibility, and it will cause avalanche effect of triggers.
> Revert "fix(apps/prod/tekton/configs/triggers): fix trigger for `monitoring` component (#936)"

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- It should avoid use different tools different with linux, may be it is not existed in the image.
- Run the remote call codes in a delicate container step, it does not depend on golang or other compile tools.
> fix(apps/prod/tekton/cofnigs/tasks): fix build step in mac machine

- apps/prod/tibuild/deployment.yaml
- deploy new tidb image to use release-x.y.z enterprise plugin branch for hotfix
> chore: deploy tidb image to use new enterprise-plugin branch for hotfix

- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/fake-git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/git-push.yaml
- operator only live for k8s, so only linux docker image is needed
> fix: tiflow-operator only for linux

- apps/prod/tekton/ingress/ingress-dashboard.yaml
- apps/prod/tekton/ingress/ingress-event-listener.yaml
- the internal hook listen on the internal ingress endpoint.
- add internal dashboard ingress to fast access the pages.
> feat(apps/prod/tekton/ingress): add internal ingress

- apps/prod/tekton/configs/tasks/pingcap-deliver-image.yaml
- apps/prod/tekton/configs/triggers/templates/_/image-push.yaml
Switch to another Deno script to solve the shortage of `yq` tool on regex test params.
Currently Deno has not offical container image for "linux/arm64" platform, we need limit the task run on "linux/amd64" nodes.
> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-deliver-image`

- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
Add trigger for LTS release branches:
- release-6.1
- release-6.5
- release-7.1
- release-7.5
Also combine the CEL interceptors to save api calls to CEL service.
In feature we can set it for all release branches.
> chore(apps/prod/tekton/configs/triggers): add trigger for release branches

- apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
- apps/prod/tekton/configs/triggers/triggers/_/ctl/harbor.http
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/test.http
- The pushing of tidb OCI artifacts will trigger the building for `ctl` component.
- When building it, it juge version with tidb.git repo.
> chore(apps/prod/tekton/configs/triggers): add trigger for `ctl` building

- apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
- enale sync rc image to qa. 
- eg. hub.pingcap.net/tikv/pd/image:release-x.x -> hub.pingcap.net/qa/pd:release-x.x
> feat: enable release-x.x image sync to qa repo

- apps/prod/tibuild/deployment.yaml
Why:
- tibuild pod usually restart
- our k8s network sometimes will be slow, so just loose the timeout
> chore: lease timeout check to avoid too much restart

- apps/prod/tibuild/deployment.yaml
Why:
- upgrade tibuild to trigger tekton
> chore: upgrade tibuild

- apps/prod/jenkins/release/values-controller.yaml
bump jenkins lts version to 2.426.3 to fix security issues.
> feat(apps/prod/jenkins): bump jenkins lts version to 2.426.3

- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
- new pipeline is not ready for older version yet
- disable trigger for release-6.5 and release-6.1
> fix: do not build for older release version

- apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
pull from dockerhub directly will
- use internet bandwidth
- meet 'TOOMANYREQUESTS: You have reached your pull rate limit'
- pull dockerhub image through PingCAP internal mirror
> feat: use dockerhub through internal mirror

- apps/prod/cloudevents-server/release.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/94
> fix(apps/prod/cloudevents-server): bump image tag to `v20240228-8-g6a29275`

- apps/prod/tekton/setup/dashboard/kustomization.yaml
- apps/prod/tekton/setup/dashboard/release.yaml
- apps/prod/tekton/setup/kustomization.yaml
- apps/prod/tekton/setup/pipeline/kustomization.yaml
- apps/prod/tekton/setup/pipeline/release.yaml
- apps/prod/tekton/setup/triggers/interceptors.yaml
- apps/prod/tekton/setup/triggers/kustomization.yaml
- apps/prod/tekton/setup/triggers/release.yaml
the k8s yaml files are prepared from:
- pipeline: https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.39.0/release.yaml
- triggers: 
- https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.2/release.yaml 
-  https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.2/interceptors.yaml
- dashboard(modify the `--read-only` arg): https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.28.0/tekton-dashboard-release.yaml
> refactor(apps/prod/tekton/setup): prepare for hacked event listener image

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml
Reverts PingCAP-QE/ee-ops#1052
> Revert "fix(apps/prod/tekton/configs/pipelines): use checkout result as commit sha to downstream tasks"

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
Why: length must be no more than 63 characters for `metadata.name`
> test(apps/prod/tekton/configs/triggers): fix trigger name length issue

- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
currently ours oci registry can not support standalong blob push, so we workaround it by this way.
> fix(apps/prod/tekton/configs/tasks): support GA for tiup pkgs

- apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml
reserve for darwin machine resource releasing.
> tests(apps/prod/tekton/configs/triggers/templates):  reserve timeout for finally task

- charts/prow/Chart.yaml
- charts/prow/templates/components/deck/deployment.yaml
- charts/prow/templates/components/hook/deployment.yaml
- charts/prow/templates/components/tide/deployment.yaml
> chore(charts/prow): update the probles

- apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
`tiup -v` depends on mirror setting.
> fix(apps/prod/tekton/configs/tasks): fix tiup command

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
Reverts PingCAP-QE/ee-ops#1137
No nightly release found  in mirror, only have stable releases.
> Revert "feat(apps/prod/tekton/configs/tasks): add env var `RUSTUP_DIST_SERVER` in binary building step"

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
> fix(apps/prod/tekton/configs/tasks): add cleanup step when the task timeouted or failed.

- apps/prod/tekton/configs/pvcs/cargo-home.yaml
Reverts PingCAP-QE/ee-ops#1140
```
Caused by:
File exists (os error 17)
+ r=101
+ set +x
make[2]: *** [Makefile:459: x-build-dist] Error 101
make[2]: Leaving directory '/workspace/source/tikv'
make[1]: *** [Makefile:270: build_dist_release] Error 2
make[1]: Leaving directory '/workspace/source/tikv'
make: *** [Makefile:259: dist_release] Error 2
```
> Revert "feat(apps/prod/tekton/configs/pvcs): add global crate index mirror"

- apps/gcp/prow/release/release.yaml
Fix dco plugin to ignore merge type commits.
> fix(apps/gcp/prow/release): bump hook to v20240614-fd27fb709

- apps/prod/harbor/release/release.yaml
> fix(apps/prod/harbor/release): try to solve uploading issue with `chunksize` param

- apps/prod/tekton/configs/triggers/triggers/_/git-push-on-fips-branches.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
> fix(apps/prod/tekton/configs/triggers): disable tiflash mac target builds

- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-push.yaml
> feat(pingcap/tidb-operator): add trigger for branches and tags

- apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml
___
Bug fix
___
- Added `--delete -f` flags to `ks3util sync` command in `git-push.yaml` to ensure proper cache synchronization.
___
<tr>
<td>
<details>
<summary><strong>git-push.yaml</strong><dd><code>Fix cache sync task with additional flags</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml
- Added `--delete -f` flags to `ks3util sync` command.
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ee-ops/pull/1176/files#diff-0be829dd6735a25ee2dcd …
> fix(pingcap-qe/artifacts): fix cache sync task

- apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml
- apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
___
Enhancement, Configuration changes
___
- Added `force-builder-image` parameter to pipeline and task configurations to support custom builder images.
- Updated branch push, PR, and tag create triggers to extract `builder-image` from headers and include `force-builder-image` parameter.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pingcap-build-package.yaml</strong><dd><code>Add force-builder-image parameter to pipeline configuration</code></dd></summary>
<hr>
apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml
<li>Added <code>force-builder-image</code> parameter to specify a custom builder image.<br> <li> …
> feat(apps/prod/tekton/configs): support tibuild trigger with custom builder image

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
___
Bug fix
___
- Corrected the parameter name from `force-builder-image` to `builder-image` in the following trigger configurations:
- fake-github-branch-push
- fake-github-pr
- fake-github-tag-create
___
<tr>
<td>
<details>
<summary><strong>fake-github-branch-push.yaml</strong><dd><code>Fix parameter name in fake-github-branch-push trigger configuration</code></dd></summary>
<hr>
apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
<li>Corrected the parameter name from <code>force-builder-image</code> to <br><code>builder-image</code>.<br>
</details>
</td>
<td><a …
> fix(apps/prod/tekton/configs/triggers/triggers): fix binding for triggers

- apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
- apps/prod/tekton/configs/tasks/gen-build-binaries-scripts.yaml
- apps/prod/tekton/configs/tasks/gen-build-images-scripts.yaml
- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
- apps/prod/tekton/configs/tasks/pingcap-auto-add-image-major-tag.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
- apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml
- apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
___
dependencies
___
- Updated the Docker image tag for `ghcr.io/pingcap-qe/cd/utils/release` to `v20240325-60-gb6f8928` across multiple Tekton pipeline and task configuration files.
- Ensured consistency in the Docker image version used in various tasks including `pingcap-release-ga`, `gen-build-binaries-scripts`, `gen-build-images-scripts`, `multi-arch-image-collect`, `pingcap-auto-add-image-major-tag`, `pingcap-build-binaries-darwin`, `pingcap-build-binaries`, `pingcap-build-images`, `pingcap-compose-offline-pkgs`, `pingcap-get-builder-image`, `publish-tiup-from-oci-artifact`, `create-pr-to-add-release-anchor-commit`, and `create-pr-to-bump-tikv-version`.
___
<table><thead><tr><th></th><th align="left">Relevant …
> chore(deps): update  ghcr.io/pingcap-qe/cd/utils/release docker tag to v20240325-60-gb6f8928

- apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
- apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
avoid timeout on low performance mac machines.
___
Enhancement
___
- Increased the pipeline run timeout to 3 hours for `tiflash` and `tikv` components to avoid timeouts on low-performance Mac machines.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>git-push.yaml</strong><dd><code>Increase pipeline run timeout for tiflash to 3 hours</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
- Increased the pipeline run timeout from 2 hours to 3 hours.
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ee-ops/pull/1183/files#diff-6e78f263 …
> chore(apps/prod/tekton/configs/triggers): increase pipeline run timeout to 3h

- apps/prod/dl/release.yaml
support fetch private repo with OCI credential configuration.
> feat(apps/prod/dl): bump docker image `ghcr.io/pingcap-qe/ee-apps/dl` to `v20240228-71-g6dcfc9c`

- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
> fix(apps/prod/tekton/configs/tasks): use the mirror registry to download oci files

- apps/gcp/prow/release/release.yaml
> fix(apps/gcp/prow/release): sticky lgtm label for `pingcap/tidb-tools` repo

- apps/prod/jenkins/pre/cronjobs.yaml
- apps/prod/tekton/configs/tasks/hotfix/create-pr-to-sync-owners.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml
- apps/staging/jenkins/pre/obc/cronjobs.yaml
> chore(deps): bump docker images denoland/deno to `1.45.5`

- apps/prod/jenkins/pre/cronjobs.yaml
- apps/prod/jenkins/pre/obc/obc.yaml
- apps/prod/jenkins/pre/secret.yaml
the previous can not be GC well.
> fix(jenkins/release/jenkins): use another ci cache bucket

- apps/prod/jenkins/pre/obc/obc.yaml
the previous can not be GC well.
> fix(jenkins/release/jenkins): delete obc `ci-pipeline-cache`

- apps/prod/jenkins/release/values-controller.yaml
Java 11 EOL is 2024-09 for jenkins LTS.
> fix(jenkins/release/jenkins): upgrade to jdk17 edition

- apps/prod/jenkins/release/values-controller-plugins.yaml
> fix(jenkins/release/jenkins): overwrite plugins with list in GitOps

- apps/prod/tibuild/deployment.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/164
> fix(apps/prod/tibuild): bump docker image to v20240228-72-gd319bf4

- apps/gcp/prow/release/release.yaml
Ref: https://github.com/ti-community-infra/tichi/pull/1188
> chore(apps/gcp/prow): update docker image of cherry-picker plugin to v2.4.4

- apps/prod/tekton/configs/triggers/triggers/_/harbor/artifact-push-on-harbor.yaml
limit it to special new harbor instance.
> chore(apps/prod/tekton/configs/triggers): limit oci artifacts push event resource url (#1223)

- apps/gcp/prow/release/release.yaml
> fix(apps/gcp/prow/release): bump image tag for needs-rebase plugin and ghproxy service

- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
Ref: https://github.com/PingCAP-QE/artifacts/pull/396
> feat(apps/prod/tekton/configs/tasks): add params `force-version` in task `publish-tiup-from-oci-artifact`

- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
> fix(apps/prod/tekton/configs/triggers): fix trigger git-push-pingcap-tidb-enterprise-without-plugins

- apps/prod/cloudevents-server/release.yaml
Ref: 
- https://github.com/PingCAP-QE/ee-apps/pull/165
- https://github.com/PingCAP-QE/ee-apps/pull/168
> chore(apps/prod/cloudevents-server): bump docker image tag to `v20240228-76-geadd400`

- apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-push-experiment.yaml
> fix(apps/prod/tekton/configs/triggers): fix tiggers for ng-monitoring

- apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
> chore(apps/prod/tekton/configs/triggers): tmp disable sync for lt v8.x images

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
Try to address the mirror issue:
```log
info: latest update on 2023-12-28, rust version 1.77.0-nightly (89e2160c4 2023-12-27)
info: downloading component 'cargo'
error: component download failed for cargo-aarch64-unknown-linux-gnu: could not download file from 'https://mirrors.ustc.edu.cn/rust-static/dist/2023-12-28/cargo-nightly-aarch64-unknown-linux-gnu.tar.xz' to '/root/.rustup/downloads/842067905bb35f5ecd6bedd36c1400dc8d125b9d077df2d8b3b704a4cfc8de35.partial'
+ r=1
+ set +x
make[2]: *** [Makefile:459: x-build-dist] Error 1
make[2]: Leaving directory '/workspace/source/tikv'
make[1]: *** [Makefile:270: build_dist_release] Error 2
make[1]: Leaving directory '/workspace/source/tikv'
make: *** [Makefile:259: dist_release] Error 2
```
> fix(apps/prod/tekton/configs/tasks): replace rustup mirror

- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
builds failed in fetch the date nightly toolchain
> fix(apps/prod/tekton/configs/tasks): disable rustup mirror

- apps/prod/tekton/configs/tasks/pingcap-git-clone-ext.yaml
before:
```
~/tidb # MAJOR_MINOR_PATCH=$(echo "$RELEASE_VERSION" | awk -F. '{print $1 "." $2 "." $3}')
~/tidb # echo $MAJOR_MINOR_PATCH
v7.5.2-20240705-eaff0fb
```
after:
```
~/tidb #  MAJOR_MINOR_PATCH=$(echo "$RELEASE_VERSION" |grep -oE "^v[0-9]+[.][0-9]+[.][0-9]+")
~/tidb # echo $MAJOR_MINOR_PATCH
v7.5.2
```
> fix(apps/prod/tekton/configs/tasks): fix `clone-ext` for hotfix cases

- apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml
Avoid route in RC build logic, like this:
This pull request includes a small change to the `apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml` file. The change updates the regular expression used to filter git tags to include additional patterns.
* [`apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml`](diffhunk://#diff-21d26239b230e9f59b49651c03f88f72918acb020b89a894985105b787ec31feL25-R25): Updated the regular expression in the `grep -vE` command to include tags with date and hash patterns.
> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-get-set-release-version` for hotfix cases

- apps/prod/kustomization.yaml
- apps/prod/tiup-publisher/kustomization.yaml
- apps/prod/tiup-publisher/release-prod-mirror.yaml
- apps/prod/tiup-publisher/release-staging-mirror.yaml
This pull request adds a new service, `tiup-publisher`, to the production environment. The changes include updates to the kustomization files and the addition of HelmRelease configurations for both production and staging mirrors.
* [`apps/prod/kustomization.yaml`](diffhunk://#diff-ee20854a69c2a0d1fcc07e8216c968e5895b76a9f9ffc942a8aa69a9747354e5R25): Added `tiup-publisher` to the list of resources.
* [`apps/prod/tiup-publisher/kustomization.yaml`](diffhunk://#diff-54630566ef0b0b3c9dcdcd9d06b3bb924fc49d8a20364ea78c06c21a8fea5cfbR1-R5): Created a new kustomization file for `tiup-publisher` with references to `release-prod-mirror.yaml` and `release-staging-mirror.yaml`.
* [`apps/prod/tiup-publisher/release-prod-mirror.yaml`](diffhunk://#diff-6e5ab966061a7a1c3ec666fc99421d86aa4ce2aba340522ff22e …
> feat(apps/prod): add tiup-publisher

- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
This pull request includes a small but important change to the `create-pr-to-bump-tikv-version.yaml` file in the `spec` directory. The change addresses an issue where the prow plugin removes the approved label by adding a delay and reapplying the necessary labels.
* [`apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml`](diffhunk://#diff-a96c12396451377af34efa48805fc711eed0d71f0d6b51a4c6f94a0fa91edb85R128-R133): Added a sleep command and logic to reapply the `lgtm`, `approved`, and `cherry-pick-approved` labels to the pull request after creation.
> fix(apps/prod/tekton/configs/tasks/release): avoid label be removed by prow plugins

- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
Solve the `cargo_edit` crate installation error in v7.5.x
> fix(apps/prod/tekton/configs/tasks): fix task `create-pr-to-bump-tikv-version`

- apps/prod/publisher/release-prod-mirror.yaml
- apps/prod/publisher/release-staging-mirror.yaml
> fix(apps/prod/publisher): fix publisher config

- apps/prod/tekton/configs/tasks/kustomization.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml
- apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml
- make fast and stable for staging nightly ad RC tiup pkg publishing
- make fast and stable for GA tiup pkg publishing.
- rate limit for nightly is not implemented yet, so we still use old way for prod nightly publising.
> refactor(apps/prod/tekton/configs): use delicated publisher to fast tiup publishing

- apps/prod/publisher/release-prod-mirror.yaml
- apps/prod/publisher/release-staging-mirror.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml
This pull request includes updates to several deployment and configuration files to use a new version of the `ghcr.io/pingcap-qe/ee-apps/publisher` Docker image.
Version updates:
* [`apps/prod/publisher/release-prod-mirror.yaml`](diffhunk://#diff-f22fa4fd4140f21f430eb3072f127a57a662acf1775d789a8babd5827f8c8d95L27-R27): Updated the Docker image tag to `v2024.10.14-5-ge877e83` (`spec:`).
* [`apps/prod/publisher/release-staging-mirror.yaml`](diffhunk://#diff-92e3225aae1ed300717cbb62eee36a88f1eddebffe04135866e9244c65a38fdeL27-R27): Updated the Docker image tag to `v2024.10.14-5-ge877e83` (`spec:`).
* [`apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml`](diffhunk://#diff-590004973598b5b2b28d13c9d43b1b06d4f5a9dc1b772608b1ad7cea64d9f808L29-R29): Updated the Docker image tag …
> chore(apps/prod/publisher,apps/prod/tekton/configs): bump docker image ghcr.io/pingcap-qe/ee-apps/publisher to `v2024.10.14-5-ge877e83`

- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml
fix task result value when go return nil array.
> fix publish-tiup-from-oci-artifact-v2.yaml

- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
This pull request includes a change to the `create-pr-to-bump-tikv-version.yaml` file to improve the logic for determining the version of `cargo-edit` to install.
* [`apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml`](diffhunk://#diff-a96c12396451377af34efa48805fc711eed0d71f0d6b51a4c6f94a0fa91edb85L74-R84): Replaced the `if` statement with a `case` statement to more clearly handle different branch names and their corresponding `cargo-edit` versions.
> fix(apps/prod/tekton/configs/tasks): fix bump tikv version pr task

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
> fix(apps/prod/tekton/configs/triggers): support devbuild to trigger darwin targets

- apps/prod/tekton/configs/triggers/bindings/github-pr.yaml
Comment the `pr-author` in the binding `github-pr` to compatible with TiBuild stories.
> fix(apps/prod/tekton/configs/triggers/bindings): fix binding `github-pr`

- apps/prod/tibuild/deployment.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/194
> chore(deps): bump docker image for tibuild to v2024.11.4-3-gcec492f

- apps/prod/tibuild/deployment.yaml
This pull request includes a small change to the `apps/prod/tibuild/deployment.yaml` file. The change updates the container image version for `tibuild`.
* [`apps/prod/tibuild/deployment.yaml`](diffhunk://#diff-7a638a35c3081658c6becc5d69691497c6d2b9ac58c12e048678f1c5d59dd094L23-R23): Updated the container image version from `v2024.11.4-3-gcec492f` to `v2024.11.4-4-g31622fb`.
> chore(apps/prod/tibuild): bump docker image tag to v2024.11.4-4-g31622fb

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
The cloud events can not support extension header
with "-" chars, only support a-z and A-Z and
number chars.
> fix(apps/prod/tekton/configs/triggers): fix fake github triggers

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml
> fix(apps/prod/tekton/configs): fix pipeline and templates for custom builder image support

- apps/prod/cloudevents-server/release.yaml
This pull request updates the Docker image tag for the `cloudevents-server` in the `release.yaml` file.
* [`apps/prod/cloudevents-server/release.yaml`](diffhunk://#diff-8a4c3e74c2f6de5e90a075b75bfac27a046bd7b89d0564d0b889ac6e49029cfaL41-R41): Updated the Docker image tag from `v20240228-76-geadd400` to `v2024.11.4-6-g495e6f0`.
> chore(deps): bump docker image ghcr.io/pingcap-qe/ee-apps/cloudevents-server to v2024.11.4-6-g495e6f0

- apps/prod/jenkins/pre/cronjobs.yaml
Add cronjob to monitor s3 code cache size.
> feat(prod/jenkins): add cronjob to monitor s3 codecache size

- apps/prod/tekton/configs/tasks/ci/ci-helper-for-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/github-pr-labeled.yaml
For expiremental purpose, we need to add ci helper for some future features.
> feat(apps/prod/tekton/configs): add ci helper triggers

- apps/gcp/prow/release/release.yaml
reduce the frequent for scanning all PRs.
> fix(apps/gcp/prow): reduce the frequent of scanning all PRs for `needs-rebase` plugin

- apps/prod/tekton/configs/tasks/kustomization.yaml
- apps/prod/tekton/configs/tasks/publish-fileserver-from-oci-artifact.yaml
- apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-fileserver.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/_/harbor/artifact-push-on-harbor.yaml
> feat(apps/prod/tekton/configs): add task and trigger to publish files to fileserver from oci artifact

- apps/prod/cloudevents-server/release.yaml
> fix(apps/prod/cloudevents-server): bump cloudevents-server image version to `v2024.11.4-11-g58aa19e`

- apps/prod/cloudevents-server/release.yaml
Reverts PingCAP-QE/ee-ops#1337
> Revert "fix(apps/prod/cloudevents-server): bump cloudevents-server image version to `v2024.11.4-11-g58aa19e`"

- apps/prod/jenkins/pre/cronjobs.yaml
update to remove the extra double quotation marks in yaml args.
> fix(jenkins/cronjob): update to remove the extra double quotation marks

- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
> fix(apps/prod/tekton/configs/tasks): fix task multi-arch-image-collect for hotfix stories

- apps/prod/jenkins/release/values-JCasC.yaml
- apps/prod/jenkins/release/values-controller-plugins.yaml
- apps/prod/jenkins/release/values-controller.yaml
> fix(apps/prod/jenkins): bump jenkins to v2.462.3

- apps/prod/jenkins-beta/release/values-JCasC.yaml
add a new file credential for ks3util
ref https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials#example
> chore(prod/jenkins-beta): add a new file credential for ks3util

- apps/prod/jenkins/release/values-controller.yaml
> chore(prod/jenkins): debug jenkins start oom

- apps/prod/jenkins/release/values-controller.yaml
> chore(prod/jenkins): adjust jvm xmx to 16g

- apps/prod/jenkins/release/values-JCasC.yaml
> debug(prod/jenkins): comment cloudevents

- apps/prod/jenkins/release/values-JCasC.yaml
use base64 to correct read file credentials.
> fix(prod/jenkins): correct read file credentials

- apps/prod/tekton/configs/pipelines/kustomization.yaml
- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin-v2.yaml
- apps/prod/tekton/configs/tasks/kustomization.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin-v2.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
- combine multi tasks into one task: acquire resource then build with
the resource machine then release the resource.
- just use deno for run for build.
based on implement: https://github.com/PingCAP-QE/artifacts/pull/503
> feat(apps/prod/tekton/configs/pipelines): add a new darwin build pipeline

- apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml
switch to pipeline: `pingcap-build-package-darwin-v2`
> feat(apps/prod/tekton/configs): switch to new darwin build pipeline in trigger templates

- apps/prod/tekton/configs/tasks/pingcap-deliver-image.yaml
Now only `latest` exists on the repo.
> fix(apps/prod/tekton/configs/tasks): update image tag of crane

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin-v2.yaml
> refactor(apps/prod/tekton/configs/pipelines): make results of darwin pipeline be same with linux pipeline

- apps/prod/jenkins/pre/cronjobs.yaml
correct read env from secret in cronjob
> fix(clean-code-cache): correct read env from secret in cronjob

- apps/gcp/prow/release/release.yaml
bump the crier image to include the fix for jenkins url link in presubmit jobs
> fix(apps/gcp/prow/release): fix jenkins url link pr context

- apps/gcp/prow/release/release.yaml
fix the ci link issue for pending status in GitHub.
> fix(apps/gcp/prow/release): update jenkins-operator image

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
- apps/prod/tekton/configs/triggers/triggers/_/harbor/artifact-push-on-harbor.yaml
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/_/git-create-branch.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/_/git-create-tag.yaml
- apps/prod/tekton/configs/triggers/triggers/pingcap/ticdc/git-push.yaml
This pull request includes updates to several Tekton configuration files to add support for the `pingcap/ticdc` repository. The changes involve adding `pingcap/ticdc` to various filters and updating resource specifications for the repository.
Key changes include:
* [`apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml`](diffhunk://#diff-568be39468441f09f11d91d4c71d77c96952fb478d3695735af6b02f24cb8969L14-R20): Added `pingcap/ticdc` to the repository filter and updated resource specifications for timeout, source-ws-size, builder-resources-cpu, and builder-resources-memory. [[1]](diffhunk://#diff-568be39468441f09f11d91d4c71d77c96952fb478d3695735af6b02f24cb8969L14-R20) [[2]](diffhunk://#diff-568be39468441f09f11d91d4c71d77c96952fb478d3695735af6b02f24cb8969R31) …
> build(pingcap/ticdc): add build triggers

- apps/prod/tekton/configs/triggers/triggers/_/github-pr-labeled-with-needs-ok-to-test.yaml
add more repos to make the PRs on them to be added `ok-to-test` label automatically for given contributors.
> chore(apps/prod/tekton/configs/triggers): update trigger for more repos

- apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-push.yaml
This pull request includes a small but important change to the `git-push.yaml` configuration file. The change updates the branch matching pattern to include a new branch for triggering actions.
* [`apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-push.yaml`](diffhunk://#diff-3ca1bad252676f3082e361e731ac95e805883b344a366d3b27d5092ad5e51eddL19-R19): Updated the branch matching pattern to include `feature/v2` in addition to `master` and `release-*` branches.
> feat(pingcap/tidb-operator): add trigger for git push on `feature/v2` branch

- apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
- apps/prod/tekton/configs/tasks/gen-build-binaries-scripts.yaml
- apps/prod/tekton/configs/tasks/gen-build-images-scripts.yaml
- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
- apps/prod/tekton/configs/tasks/pingcap-auto-add-image-major-tag.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-linux.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
- apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml
- apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml
- apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml
- apps/prod/tekton/configs/tasks/pingcap-upload-offline-package.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
- apps/prod/tekton/configs/tasks/release/tag-rc2ga-on-oci-artifacts.yaml
- apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml
- apps/prod/tekton/configs/tasks/release/wait-delivery-tiup.yaml
prepare for compatible with future object storage providers.
> feat(apps/prod/tekton/configs): use aws-cli to upload to qiniu

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
This pull request includes changes to the Tekton trigger configurations to improve the handling of the `profile` parameter. The main updates involve reading the `profile` parameter from the header or defaulting to 'release' and ensuring that the `profile` parameter is correctly passed to the bindings.
Key changes:
* [`apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml`](diffhunk://#diff-568be39468441f09f11d91d4c71d77c96952fb478d3695735af6b02f24cb8969L64-R77): Updated the `custom-params` to include the `profile` parameter from the header or default to 'release', and modified the binding to use `$(extensions.custom-params.profile)` for the `profile` parameter.
* [`apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml`](diffhunk://#dif …
> feat(apps/prod/tekton/configs/triggers): parse `profile` param from cloud event extension

- apps/prod/tibuild/deployment.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/222
> chore(apps/prod/tibuild): bump tibuild image tag to `v2024.12.12-9-g8a17a7b`

- apps/gcp/prow/release/release.yaml
- cherrypicker, ref: https://github.com/ti-community-infra/tichi/pull/1192
- issue-triage, ref: https://github.com/ti-community-infra/tichi/pull/1193
> chore(apps/gcp/prow): bump external plugin version

- apps/prod/chatops-lark/kustomization.yaml
- apps/prod/chatops-lark/release.yaml
- apps/prod/kustomization.yaml
This pull request introduces a new HelmRelease for the `chatops-lark` application and updates the kustomization files to include this new resource. The most important changes include the addition of `chatops-lark` to the kustomization resources and the detailed configuration of the HelmRelease.
Additions to kustomization and HelmRelease configuration:
* [`apps/prod/chatops-lark/kustomization.yaml`](diffhunk://#diff-4119b17540b0e13598661402ee1efba2b16ef8512cab59ab1f20a80bc40646eaR1-R5): Created a new kustomization file for the `chatops-lark` application.
* [`apps/prod/chatops-lark/release.yaml`](diffhunk://#diff-20c9387c8f1e6985fb4d41f78c9b9b82835b612abbd3e778c45947b2de277079R1-R46): Added detailed HelmRelease configuration for `chatops-lark`, including chart specifications, installation …
> feat(apps/prod): deploy chatops lark bot

- apps/prod/chatops-lark/release.yaml
ref https://github.com/PingCAP-QE/ee-apps/pull/238
This pull request includes updates to the `apps/prod/chatops-lark/release.yaml` file to update the chart version, enable testing, and update the image tag.
Chart and version updates:
* Updated the chart version from `0.1.1` to `0.1.2` in the `spec:` section.
Testing configuration:
* Enabled testing by changing the `enable` field from `false` to `true` in the `spec:` section.
Image updates:
* Updated the image tag from `v2025.1.30-7-gce0dddc` to `v2025.1.30-11-g3b74562` in the `spec:` section.
> chore(apps/prod/chatops-lark): bump chart release with new image

- apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/prod/tekton/configs/pipelines/pingcap-build-package-linux.yaml
- apps/prod/tekton/configs/tasks/pingcap-get-set-release-version-v2.yaml
This pull request includes updates to the Tekton pipeline configuration files and a task script to use a new version of a task and improve tag handling.
Updates to pipeline configuration:
* [`apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml`](diffhunk://#diff-4375ee3268c7e5b103a5849b55d25ff2d4a9167389910c0e5836865cd14b392aL110-R110): Updated `taskRef` to use `pingcap-get-set-release-version-v2` instead of the previous version.
* [`apps/prod/tekton/configs/pipelines/pingcap-build-package-linux.yaml`](diffhunk://#diff-ce766b7b64adef72b7b3a177ad33e24ec5a6296eaea73fab93e0473927bed22bL111-R111): Updated `taskRef` to use `pingcap-get-set-release-version-v2` instead of the previous version.
Improvements to tag handling:
* …
> chore(apps/prod/tekton/configs/pipelines): use pingcap-get-set-release-version-v2 in pipeline

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
devbuild will send fake GitHub events with a new header named 'ce-paramPlatform'.
> feat(apps/prod/tekton/configs/triggers): add single platform build tiggers for devbuild

- apps/prod2/coder/release/release.yaml
This pull request updates the Helm chart version in the `release.yaml` file to ensure the application uses the latest features and fixes.
* [`apps/prod2/coder/release/release.yaml`](diffhunk://#diff-d9857e0d055c5ef073117b02961d87ae45d567c44c51a17e4587d01e56e54542L10-R10): Updated the `chart.spec.version` from `2.18.5` to `2.21.0` to align with the latest chart release.
> chore(apps/prod2/coder/release): bump to v2.21.0

- apps/prod2/coder/workspaces/kustomization.yaml
- apps/prod2/coder/workspaces/namespace.yaml
- apps/prod2/coder/workspaces/rbac.yaml
Create namespace `coder-workspaces` and binding service account to `coder`
> chore(apps/prod2): split coder workspaces into independent namespace

- apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform-darwin.yaml
- apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform-linux.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create-single-platform.yaml
Rename and restructure trigger templates to support OS-specific builds:
- Split single-platform template into Linux and Darwin variants
- Update references to use OS-specific templates
- Add macOS SSH credentials workspace for Darwin builds
- Make pipeline reference dynamic based on OS parameter
> fix(apps/prod/tekton): add macOS single platform devbuild support

- apps/prod/tekton/configs/tasks/hotfix/create-pr-to-update-gomod-fix-ladp.yaml
- apps/prod/tekton/configs/tasks/kustomization.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/templates/pingcap/tidb/update-gomod-fix-ladp-for-hotfix-branch.yaml
- Introduced a new Tekton task `create-pr-to-update-gomod-fix-ladp` to automate  handling LDAP certificate updates for specific hotfix branches(hotfix for v7.5 & v8.1 & v8.5).
- Added a corresponding TriggerTemplate `update-pingcap-tidb-gomod-fix-ladp-for-hotfix-branch` to facilitate the execution of the task with specified parameters.
> feat(apps/prod/tekton): add task and trigger template for updating ladp crt/key in hotfix branches

- apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform.yaml
- apps/prod/tekton/configs/triggers/templates/kustomization.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create-single-platform.yaml
This pull request consolidates the Tekton TriggerTemplate configurations for single-platform builds by renaming and generalizing the `build-component-single-platform-linux.yaml` file to `build-component-single-platform.yaml`. It also introduces platform-specific parameters and updates references across related configurations.
* Renamed `build-component-single-platform-linux.yaml` to `build-component-single-platform.yaml` and updated the `metadata.name` field accordingly.
* Added platform-specific parameters, such as `boskos-server-url` for Darwin platforms and `mac-ssh-credentials` for Darwin-specific secrets, while annotating existing parameters like `cargo-home` and `cypress-cache` for Linux platforms. [[1]](diffhunk://#diff-788df9ab2dc5c1e297afef925368de9ee26f0e579af86e4cada9fb3ec09e6a6 …
> fix(apps/prod/tekton/configs/triggers): merge platform-specific build templates into single template

- apps/prod/chatops-lark/release.yaml
apply the fix in PingCAP-QE/ee-apps@c793d80
> fix(apps/prod/chatops-lark): bump image tag to v2025.4.8-26-gc793d80

- apps/gcp/prow/release/release.yaml
Ref ti-community-infra/prow@ceae038a4
> chore(apps/gcp/prow): bump tide image tag to v20250516-ceae038a4

- apps/gcp/prow/release/release.yaml
Ref ti-community/prow@ceae038a4
> fix(apps/gcp/prow): bump image for hook to v20250519-ceae038a4

- apps/gcp/prow/release/release.yaml
Relate to PR https://github.com/ti-community-infra/prow/pull/9.
Support approve gitHub action run with comment `/test all`.
> fix(apps/gcp/prow): bump hook image tag to v20250520-2df574a5

- apps/prod/tekton/configs/triggers/event-listeners/event-listener-public.yaml
This pull request updates the `event-listener-public.yaml` configuration to refine the event filtering logic for Tekton triggers. Specifically, it introduces a new filter to exclude events related to old branches during branch renaming.
* [`apps/prod/tekton/configs/triggers/event-listeners/event-listener-public.yaml`](diffhunk://#diff-1be050bd43bb23918c4becd1cf77c1644c4a7273a3a7eeb2f452233c13425897R38-R43): Added a new condition under the `params` section to filter out events where `body.after` equals `0000000000000000000000000000000000000000`, effectively excluding old branch references during branch renaming.
Close #1480
> fix(apps/prod/tekton/configs/triggers): add filter to exclude old branch on renaming

- apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml
This pull request includes a minor improvement to the `git-push.yaml` file in the `PingCAP-QE` Tekton triggers configuration. The change updates the `wget` command to save the downloaded file with the branch name as the filename before unzipping it, ensuring better file management.
* [`apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml`](diffhunk://#diff-0be829dd6735a25ee2dcd3ba6229d657d5c901e58e1debad1f228242e3563300L49-R49): Changed the `wget` command to save the downloaded file as `${branch}.zip` and then unzipped the file using the saved filename.
> fix(apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts): fix git archive download to save and unzip branch zip file

- apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
Ref: https://github.com/PingCAP-QE/artifacts/pull/630
> chore(apps/prod/tekton/configs/triggers): allow next-gen tags in Harbor image push trigger

- apps/prod/tekton/configs/tasks/hotfix/create-pr-to-update-gomod-fix-ladp.yaml
Refactor the logic for determining if a branch is a hotfix candidate for LDAP updates. Replace the `does_need_ldap_fix` flag with `is_ldap_hotfix_candidate_branch` for clarity. Enhance cherry-pick decision-making by adding checks to avoid duplicate commits and provide clearer skip reasons. Improve error handling during cherry-pick operations.
* If the current hotfix branch already contains the commits to be cherry-picked or related LDAP certs update commits, then skip the cherry-pick.
> fix(apps/prod/tekton/configs): update ldap hotfix logic in create-pr task

- apps/prod/tibuild/deployment.yaml
This pull request updates the container image version in the `tibuild` deployment configuration to ensure the application uses the latest build.
* [`apps/prod/tibuild/deployment.yaml`](diffhunk://#diff-7a638a35c3081658c6becc5d69691497c6d2b9ac58c12e048678f1c5d59dd094L23-R23): Updated the container image from `tibuild:v2025.4.8-27-gd38ba90` to `tibuild:v2025.6.8-1-g78867b3` in the deployment specification.
Ref pingcap-qe/ee-apps@78867b3
> fix(apps/prod/tibuild): bump image tag to `v2025.6.8-1-g78867b3`

- apps/prod/tekton/configs/triggers/event-listeners/event-listener-internal.yaml
- apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
This pull request updates Tekton configuration files to expand the scope of repository namespaces and repository names that are filtered in event listeners and triggers. The changes primarily involve adding support for the `devbuild` namespace and its sub-repositories.
Updates to repository filtering:
* [`apps/prod/tekton/configs/triggers/event-listeners/event-listener-internal.yaml`](diffhunk://#diff-af52c5304ea150486e9610c3415ee2e1b34e00328200026f5e83dde768242452L19-R19): Added `devbuild` to the list of allowed repository namespaces for filtering `PUSH_ARTIFACT` events.
* [`apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml`](diffhunk://#diff-2756d1501a259945f67d401c020a0845798ce98d0bdfc135d6a2345cd34c1204L16-R16): Expanded repository name matching to include …
> feature(apps/prod/tekton/configs/triggers): add devbuild namespace to Tekton event filters

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
This pull request updates several Tekton trigger configurations to include support for the `pingcap/tidb-operator` repository. Changes have been made across multiple files to add `pingcap/tidb-operator` to the repository filters and specify its resource requirements and timeout values.
* Added `pingcap/tidb-operator` to the list of repositories in the `filter` parameter across multiple trigger configurations, ensuring it is processed by the relevant pipelines. (`fake-github-branch-push-single-platform.yaml`: [[1]](diffhunk://#diff-9f6aafe661ca69015d119375f5de54fd57e71c13bff121900c949b7da4e4ea44L14-R14) `fake-github-branch-push.yaml`: [[2]](diffhunk://#diff-568be39468441f09f11d91d4c71d77c96952fb478d3695735af6b02f24cb8969L14-R14) `fake-github-pr-single-platform.yaml`: …
> feat(triggers/fake-github): add overlays for pingcap/tidb-operator to all triggers (branch-push, tag-create, pr, single-platform)

- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create-single-platform.yaml
- apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
This PR adds support for the following repositories to all fake-github triggers (branch-push, tag-create, PR, and single-platform):
- pingcap/ng-monitoring
- pingcap/tidb-binlog
- pingcap/tidb-tools
The overlays and filter lists now include these repos with the correct resource values based on their official triggers.
Also includes previous support for pingcap/tidb-operator overlays.
---
- Adds timeout, ws-size, CPU, and memory overlays for each repo
- Updates all relevant fake-github trigger YAMLs
> feat(triggers/fake-github): add overlays for ng-monitoring, tidb-binlog, and tidb-tools to all triggers

- apps/prod/tibuild/deployment.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/issues/299
> chore: bump tibuild image tag to v2025.6.22-1-g05782e8

- apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml
This PR updates the TiKV tag trigger regex pattern to support tags with `.pre` suffix (e.g., `v9.0.0-beta.2.pre`).
The updated regex pattern now properly matches tags like:
- v9.0.0-alpha.1.pre
- v9.0.0-beta.2.pre
- v9.0.0-rc.3.pre
This ensures that the CI/CD pipeline will be triggered correctly for these tag formats.
> fix(trigger): support pre-release tags with .pre suffix

- .ci/OWNERS
- OWNERS
- OWNERS_ALIASES
- apps/OWNERS
- apps/prod2/kustomization.yaml
- charts/OWNERS
- clusters/OWNERS
- infrastructure/OWNERS
- infrastructure/prod2/OWNERS
- infrastructure/prod2/kustomization.yaml
- infrastructure/prod2/nfs-pvc-provisioner/kustomization.yaml
- infrastructure/prod2/nfs-pvc-provisioner/namespace.yaml
- infrastructure/prod2/nfs-pvc-provisioner/pvc.yaml
- infrastructure/prod2/nfs-pvc-provisioner/release.yaml
- infrastructure/prod2/nginx/kustomization.yaml
- infrastructure/prod2/nginx/release.yaml
- infrastructure/prod2/openebs/diskpools.yaml
- infrastructure/prod2/openebs/release.yaml
- infrastructure/prod2/openebs/source.yaml
- infrastructure/prod2/secret-generator/release.yaml
This pull request includes updates to ownership files and infrastructure configurations, with notable changes to the `OWNERS` structure and enhancements to Kubernetes resource definitions. The most significant updates involve restructuring ownership aliases, adding new resources for provisioning, and modifying namespace configurations for Helm releases.
* Restructured `OWNERS` and `OWNERS_ALIASES` files to introduce aliases for reviewers and approvers, such as `sig-root-approvers` and `sig-root-reviewers`. Emeritus reviewers were also added as aliases. (`[[1]](diffhunk://#diff-c393dd2b18a8a597d895940893e574d6895122c4bf3ce6e2a78dbd9ca0cdd66fL1-R4)`, `[[2]](diffhunk://#diff-4985b733677adf9dda6b5187397d4700868248ef646d64aecfb66c1ced575499R1-R13)`)
* Removed individual reviewer and approver …
> feat(prod2): add NFS PVC provisioner and update namespaces in prod2 infra

- apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
Only support
- alpha version: e.g. v2.0.0-alpha.1
- beta version: e.g. v2.0.0-beta.2
- stable version: e.g. v2.0.1
> Only push tagged operator image

- apps/gcp/tekton/configs/kustomization.yaml
- apps/gcp/tekton/configs/pipelines/kaniko-build.yaml
- apps/gcp/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
- apps/gcp/tekton/configs/pipelines/pingcap-build-package-linux.yaml
- apps/gcp/tekton/configs/rbac/github-bot.yaml
- apps/gcp/tekton/configs/rbac/kustomization.yaml
- apps/gcp/tekton/configs/rbac/releaser.yaml
- apps/gcp/tekton/configs/tasks/multi-arch-image-push.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-binaries-linux.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-images.yaml
- apps/gcp/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml
- apps/gcp/tekton/configs/triggers/templates/_/build-component-single-platform.yaml
- apps/gcp/tekton/configs/triggers/templates/_/build-component.yaml
- infrastructure/prod2/openebs/test.yaml.example
This pull request includes significant updates to streamline Tekton pipeline configurations by removing unused `dockerconfig` and `git-basic-auth` workspaces, introducing new service accounts for specific tasks, and adding new resources for persistent storage and testing. Below is a breakdown of the most important changes:
* Removed `dockerconfig` and `git-basic-auth` workspaces across multiple pipeline and task configurations, simplifying workspace definitions and reducing unnecessary dependencies (`kaniko-build.yaml`, `pingcap-build-package-darwin.yaml`, `pingcap-build-package-linux.yaml`, `pingcap-build-images.yaml`, `multi-arch-image-push.yaml`, `pingcap-build-binaries-darwin.yaml`, `pingcap-build-binaries-linux.yaml`). [[1]](diffhunk://#diff-877a19ef785347957bbb69c668434e081b7801dceab …
> fix(apps/gcp/tekton/configs): switch from workspace for auth to service account methods

- apps/gcp/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml
- apps/gcp/tekton/configs/triggers/templates/_/build-component-single-platform.yaml
- apps/gcp/tekton/configs/triggers/templates/_/build-component.yaml
- apps/gcp/tekton/configs/triggers/templates/tikv/tikv/bump-tikv-cargo-pkg-version.yaml
This pull request primarily comments out several resource configurations across multiple Tekton pipeline YAML files. These changes appear to temporarily disable the use of specific secrets and persistent volume claims, such as `git-basic-auth`, `cargo-home`, and `cypress-cache`, while leaving them in the files for potential future use. Below is a categorized summary of the most important changes:
* In `apps/gcp/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml`, commented out configurations for `git-basic-auth`, `cargo-home`, and `cypress-cache` in multiple sections of the file. These resources are no longer active but remain in the file as comments. [[1]](diffhunk://#diff-7eb8a56490fe2a18d7d5d23a2b9583f4c962967a7739af3ec995e79774e6bf83L107-R115) …
> fix(apps/gcp/tekton/configs): comment out unused volume and secret mounts in trigger templates

- apps/gcp/tekton/configs/pipelines/kaniko-build.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-images.yaml
1. prepare `docker-registry` secret.
2. append the google service account key json the to the secret.
3. add the secret to the Kubernetes service account
4. run the task with the service account, Tekton pipeline controller will auto inject the volume from the `docker-registry` type secret to `/tekton/creds-secrets/<secret-name>/` path.
> fix(apps/gcp/tekton/configs): add GAR credentials env var

- infrastructure/_base/sources/helm-repo-external-secrets.yaml
- infrastructure/_base/sources/kustomization.yaml
- infrastructure/gcp/external-secrets/kustomization.yaml
- infrastructure/gcp/external-secrets/release.yaml
- infrastructure/gcp/kustomization.yaml
This pull request introduces the integration of the External Secrets Helm chart into the infrastructure, enabling automated management of external secrets. Key changes include the addition of a new Helm repository, updates to kustomization files, and the creation of a HelmRelease configuration for deploying External Secrets.
* **Addition of Helm Repository:**
- Added a new Helm repository for External Secrets in `infrastructure/_base/sources/helm-repo-external-secrets.yaml`. This repository is configured with a 24-hour sync interval and points to `https://charts.external-secrets.io`.
- Updated `resources:` in `infrastructure/_base/sources/kustomization.yaml` to include the new Helm repository file.
* **Deployment Configuration:**
- Created a `kustomization.yaml` file in …
> feat(infrastructure/gcp): add external-secrets Helm release and repository configuration

- infrastructure/gcp/external-secrets/kustomization.yaml
- infrastructure/gcp/external-secrets/release.yaml
- infrastructure/gcp/kyverno/kustomization.yaml
- infrastructure/gcp/kyverno/release.yaml
- infrastructure/prod2/external-secrets/cluster-secret-store-gcp.yaml
- infrastructure/prod2/external-secrets/kustomization.yaml
- infrastructure/prod2/external-secrets/release.yaml
- infrastructure/prod2/external-secrets/test.yaml.example
- infrastructure/prod2/kustomization.yaml
- infrastructure/prod2/namespace.yaml
This pull request introduces the External Secrets Operator to the `prod2` environment, standardizes the use of the `infra` namespace for infrastructure components, and provides example configuration for secret management. The main themes are the addition of external secrets management, namespace standardization, and related configuration updates.
**External Secrets Operator integration:**
* Added manifests for deploying the External Secrets Operator in `prod2`, including `HelmRelease` configuration (`release.yaml`), a `ClusterSecretStore` referencing GCP Secret Manager (`cluster-secret-store-gcp.yaml`), and an example `ExternalSecret` resource (`test.yaml.example`). [[1]](diffhunk://#diff-9c2c04564e056f080b9e2edefd49f9727e9ccb899ea37dfcb7d4ee4e41cc7f90R1-R45) …
> feat(infrastructure/prod2): deploy external secrets operator

- apps/gcp/prow/release/release.yaml
This pull request updates the deployment configuration for the `chatgpt` image in the `release.yaml` file. The main change is updating the image tag to use a newer version.
Deployment configuration update:
* Updated the `chatgpt` container image tag from `v20250728-3eb01d86a` to `v20250812-57374e9b9` in `apps/gcp/prow/release/release.yaml` to deploy the latest version.
> chore(apps/gcp/prow): update docker image of chatgpt plugin to `v20250812-57374e9b9`

- apps/gcp/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-binaries-linux.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-images.yaml
- apps/gcp/tekton/configs/tasks/pingcap-get-builder-image.yaml
- apps/prod/tekton/configs/tasks/gen-build-binaries-scripts.yaml
- apps/prod/tekton/configs/tasks/gen-build-images-scripts.yaml
- apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
- apps/prod/tekton/configs/tasks/pingcap-auto-add-image-major-tag.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-binaries-linux.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
- apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml
- apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml
- apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml
- apps/prod/tekton/configs/tasks/pingcap-upload-offline-package.yaml
- apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml
- apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
- apps/prod/tekton/configs/tasks/release/tag-rc2ga-on-oci-artifacts.yaml
- apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml
- apps/prod/tekton/configs/tasks/release/wait-delivery-tiup.yaml
This pull request updates the Tekton pipeline task configurations to use a newer version of the `ghcr.io/pingcap-qe/cd/utils/release` image (`v2025.8.17-13-ga5750d9`) across both GCP and production environments. This ensures consistency and access to the latest features or fixes in the build and release process.
**Image version upgrade across pipeline tasks:**
* Updated the default value of the `builder-image` or `build-image` parameters and the image used in all relevant steps to `ghcr.io/pingcap-qe/cd/utils/release:v2025.8.17-13-ga5750d9` in the following files:
* `apps/gcp/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml` [[1]](diffhunk://#diff-a09c39ae10681e079c7eb53b981261a1abd64e07e7342660568dc42818f77764L37-R37) [[2]](diffhunk://#diff-a09c39ae10681e079c7eb53b981261a1abd64e07e …
> chore(apps/gcp,apps/prod): update release utility image to v2025.8.17-13-ga5750d9

- apps/gcp/tekton/configs/pipelines/pingcap-build-package-linux.yaml
- apps/gcp/tekton/configs/tasks/pingcap-build-images.yaml
- apps/prod/tekton/configs/pipelines/pingcap-build-package-linux.yaml
- apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
This pull request adds support for handling multi-architecture (multi-arch) images in the Tekton pipelines and tasks for both GCP and production environments. The changes introduce new result fields and pipeline outputs to track multi-arch images, and update scripts to generate and collect these results.
**Multi-arch image support:**
* Added a new result field `pushed-multi-arch` in `pingcap-build-images.yaml` tasks to store information about pushed multi-arch images, along with updated descriptions for clarity. [[1]](diffhunk://#diff-441a28f898ce8d8c7d589ac267c0f029009faf4de62296fb55fd577410f1c44dL22-R27) [[2]](diffhunk://#diff-4e6ce54ff92ef3c743849aa118b675f95642e07c52395768fa6823c4bf0ed43bL19-R24)
* Updated task scripts to write empty JSON to `pushed-multi-arch` when no build script is …
> feat(apps/prod/tekton,apps/gcp/tekton): add pushed-multi-arch result to build-images tasks and pipelines

- apps/gcp/tekton/configs/tasks/pingcap-build-images.yaml
- apps/prod/tekton/configs/tasks/build/pingcap-build-images.yaml
- Change result description from "Just built and pushed" to "Built and pushed"
- Remove commented multi-arch result definition
- Directly output build results to $(results.pushed.path) instead of manual file handling
- Remove redundant echo statements and conditional checks
- Add default empty JSON output when no script exists in prod environment
depends on https://github.com/PingCAP-QE/artifacts/pull/705
> refactor(apps/gcp/tekton,apps/prod/tekton): append multi-arch tags and major tags into the result for image building

- apps/prod/tekton/configs/tasks/build/pingcap-build-binaries-darwin.yaml
- apps/prod/tekton/configs/tasks/build/pingcap-build-binaries-linux.yaml
- apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
This pull request updates Tekton build task configurations for both Darwin and Linux platforms, improving how the build output is handled when no output script or build script is present. Additionally, it restricts the scope of a Harbor image push trigger to only the `pingcap_enterprise` repository, tightening its filtering logic.
Build output handling improvements:
* In `pingcap-build-binaries-darwin.yaml` and `pingcap-build-binaries-linux.yaml`, ensures that `$(results.pushed.path)` is always populated with an empty JSON object (`"{}"`) when no output script is generated, preventing potential issues with downstream steps that expect this result. [[1]](diffhunk://#diff-6c378dc6436b0b42a90339c734e063ce27ae58531d31b9833b005d31dc07b3e7R82) …
> opt(apps/prod/tekton/configs): remove the trigger for collecting multi-arch image for migrated items

- apps/gcp/prow/release/release.yaml
Update prow-controller-manager image to ghcr.io/ti-community-infra/prow/prow-controller-manager:v20250905-a0cfed255. 
Ref  https://github.com/ti-community-infra/prow/pull/21,  fix this error:
```shell
{"component":"prow-controller-manager","error":"invalid presubmit job pull-e2e: pod spec may not use init containers","file":"sigs.k8s.io/prow/pkg/config/agent.go:371","func":"sigs.k8s.io/prow/pkg/config.(*Agent).Start.func1","jobConfig":"/etc/prow-jobs","level":"error","msg":"Error loading config.","prowConfig":"/etc/prow-config/config.yaml","severity":"error","time":"2025-09-05T03:36:32Z"}
```
> fix(apps/gcp/prow): update prow-controller-manager image to v20250905-a0cfed255

- apps/gcp/prow/release/release.yaml
update Prow hook image tag to v20250905-a0cfed255.
Ref  https://github.com/ti-community-infra/prow/pull/21,  fix this error:
```shell
{"component":"prow-controller-manager","error":"invalid presubmit job pull-e2e: pod spec may not use init containers","file":"sigs.k8s.io/prow/pkg/config/agent.go:371","func":"sigs.k8s.io/prow/pkg/config.(*Agent).Start.func1","jobConfig":"/etc/prow-jobs","level":"error","msg":"Error loading config.","prowConfig":"/etc/prow-config/config.yaml","severity":"error","time":"2025-09-05T03:36:32Z"}
```
> chore: update Prow hook image tag to v20250905-a0cfed255

- apps/gcp/prow/release/release.yaml
Update image tags for crier, sinker, deck, and status-reconciler to v20250905-a0cfed255.
To fix error from new operator pull-e2e presubmit config:
```shell
pull-e2e: pod spec may not use init containers
```
> chore(apps/gcp/prow/release): update image tags for crier, sinker, deck, and status-reconciler to v20250905-a0cfed255
