OWNERS, apps/OWNERS, charts/OWNERS, clusters/OWNERS, infrastructure/OWNERS
ref: https://www.kubernetes.dev/docs/guide/owners
=> ci: add prow OWNERS files

apps/staging/jenkins/kustomization.yaml, apps/staging/jenkins/release.yaml, apps/staging/jenkins/values-controller-ha.yaml, apps/staging/jenkins/values-controller.yaml, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-agent-svc.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/jenkins-controller-svc.yaml, charts/jenkins/values.yaml
active-standby should using other tool to manage
=> feat(charts/jenkins): active-standby mode

apps/staging/jenkins/pre/secret/cache-secret.yaml
=> fix(apps/staging/jenkins): pipeline cache endpoint

apps/prod/OWNERS, apps/prod/bazel-remote/release/release.yaml, apps/prod/jenkins/post/_base/cronjob-go-caches.yaml, apps/prod/jenkins/post/_base/kustomization.yaml, apps/prod/jenkins/post/_base/pvc.yaml, apps/prod/jenkins/post/_base/rbac.yaml, apps/prod/jenkins/post/_base/secrets.yaml, apps/prod/jenkins/post/cd/kustomization.yaml, apps/prod/jenkins/post/cd/namespace.yaml, apps/prod/jenkins/post/kustomization.yaml, apps/prod/jenkins/post/ti-pipeline/kustomization.yaml, apps/prod/jenkins/post/ti-pipeline/namespace.yaml, apps/prod/jenkins/post/ticdc/kustomization.yaml, apps/prod/jenkins/post/ticdc/namespace.yaml, apps/prod/jenkins/post/tidb-mergeci/kustomization.yaml, apps/prod/jenkins/post/tidb-mergeci/namespace.yaml, apps/prod/jenkins/post/tidb/kustomization.yaml, apps/prod/jenkins/post/tidb/namespace.yaml, apps/staging/bazel-remote/release/release.yaml, apps/staging/jenkins/post/_base/pvc.yaml, apps/staging/jenkins/post/_base/rbac.yaml, apps/staging/jenkins/post/kustomization.yaml
- current expire rule active on path `data/`
=> feat(apps/prod/jenkins): add namespaces

apps/prod/jenkins/pre.yaml, apps/prod/jenkins/pre/cronjobs.yaml, apps/prod/jenkins/pre/kustomization.yaml, apps/prod/jenkins/pre/obc.yaml, apps/prod/jenkins/pre/obc/obc.yaml, apps/prod/jenkins/pre/secret.yaml, apps/prod/jenkins/pre/secret/cache-secret.yaml, apps/prod/jenkins/release/values-JCasC.yaml, apps/staging/jenkins/pre/cronjobs.yaml, apps/staging/jenkins/pre/obc/obc.yaml
- change pipeline cache shrink job schedule to `0 2 * * *`
- updat jenkins config as code: from manual secret `cache-s3` to auto secret `jenkins-cache`
=> feat(apps/prod/jenkins): add existed OBC and secret to jenkins

.github/renovate.json
=> Revert "ci: fix renovate `versioningTemplate`"

.github/workflows/charts_test-bazel-remote.yaml, .github/workflows/charts_test-jenkins.yaml, .github/workflows/charts_test-prow.yaml, .github/workflows/charts_test.yaml, .github/workflows/gitops_test.yaml, apps/staging/prow/release.yaml, charts/prow/Chart.yaml, charts/prow/config/default-prow-config.yaml.tpl, charts/prow/templates/_helpers.tpl, charts/prow/templates/components/jenkins-operator/deployment.yaml, charts/prow/templates/components/jenkins-operator/hpa.yaml, charts/prow/templates/components/jenkins-operator/role.yaml, charts/prow/templates/components/jenkins-operator/serviceaccount.yaml, charts/prow/templates/secret-github.yaml, charts/prow/values.yaml
Ref: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/jenkins-operator
=> feat(charts/prow): add jenkins-operator comonent

apps/staging/prow/configs/jobs/PingCAP-QE/ee-ops/job2.yaml
=> chore(apps/staging/prow/configs): add job in `job2.yaml`

apps/staging/jenkins/release/values-JCasC.yaml, apps/staging/jenkins/release/values-controller-plugins.yaml
- pipeline-utility-steps:2.13.0
- http_request:1.16
=> feat(apps/staging/jenkins): add plugins

apps/prod/mongodb/kustomization.yaml, apps/prod/mongodb/release.yaml, infrastructure/prod/kustomization.yaml, infrastructure/prod/sources/helm-repo-bitnami.yaml, infrastructure/prod/sources/kustomization.yaml
prepare for migration from staging env
=> feat(apps/prod/mongodb): add deployment in production env

apps/prod/jenkins/release/values-JCasC.yaml
prepare for migrate mongodb to prod env.
=> chore(apps/prod/jenkins/release): update mongodb secret to other secret

apps/prod/jenkins/post/tidb/pvc-job.yaml, apps/staging/jenkins/post/tidb/pvc-job.yaml
ref: https://github.com/PingCAP-QE/ci/pull/1504
=> chore(apps/prod,apps/staging): update image in bazel base data pvc fresh job

apps/prod/jenkins/post.yaml, apps/staging/jenkins/post.yaml
ref: https://fluxcd.io/flux/use-cases/running-jobs/
=> fix(apps/prod,apps/staging): job update inmutable issue

infrastructure/prod/rook-ceph/release-cluster.yaml
- node should be added one by one after OSD reblanced.
=> chore(infrastructure/prod/rook-ceph): add node to ceph cluster

apps/prod/bazel-remote/pre/obc.yaml, apps/prod/bazel-remote/release/cronjobs.yaml
=> feat(apps/prod/bazel-remote): increase bazel s3 obc size

apps/prod/jenkins/post/tidb/pvc-job.yaml, apps/staging/jenkins/post/tidb/pvc-job.yaml
it must be merged before 
https://github.com/PingCAP-QE/ci/pull/1518
=> chore(apps/*/jenkins/post/tidb): update image for bazel data freshing jobs

apps/staging/prow/release/release.yaml
PR: https://github.com/kubernetes/test-infra/pull/27856
Building:
1. make build-single-image PROW_IMAGE=prow/cmd/jenkins-operator REGISTRY=hub.pingcap.net/ee
2. make push-single-image PROW_IMAGE=prow/cmd/jenkins-operator REGISTRY=hub.pingcap.net/ee
=> feat(apps/staging/prow): update jenkins-operator with built from PR code

charts/greenhouse/Chart.yaml, charts/greenhouse/values.yaml
- update image with latest greenhouse
=> feat(charts/greenhouse): update image with latest code

charts/greenhouse/Chart.yaml
=> fix(charts/greenhouse): bump image to v20221109-9447e23b56

apps/staging/jenkins/release/values-JCasC.yaml
=> feat: add codecov token

charts/greenhouse/Chart.yaml, charts/greenhouse/templates/tests/test-connection.yaml
=> feat(charts/greenhouse): add test hook

charts/README.md, charts/ats/.helmignore, charts/ats/Chart.yaml, charts/ats/templates/NOTES.txt, charts/ats/templates/_helpers.tpl, charts/ats/templates/deployment.yaml, charts/ats/templates/hpa.yaml, charts/ats/templates/ingress.yaml, charts/ats/templates/service.yaml, charts/ats/templates/serviceaccount.yaml, charts/ats/templates/tests/test-connection.yaml, charts/ats/values.yaml
ATS: [apache traffic server](https://trafficserver.apache.org/)
=> feat(charts/ats): create ats chart

apps/prod/ats/config-override/storage.config
current cluster disk size is not enough
=> fix(apps/staging/prod): reduce ats disk size

apps/prod/ats/config-override/storage.config
=> Revert "fix(apps/staging/prod): reduce ats disk size"

apps/staging/goproxy/goproxy-deployment.yaml, apps/staging/goproxy/goproxy-storage.yaml, apps/staging/goproxy/goproxy-svc.yaml, apps/staging/goproxy/kustomization.yaml, apps/staging/kustomization.yaml
=> feat(apps/staging): deploy goproxy

apps/prod/ats/config-override/records.config, apps/staging/ats/config-override/records.config
Ref: https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-cache-ram-cache-algorithm
=> feat(apps/*/ats): using CLFUS algorithm for ram cache

apps/prod/jenkins/post/tidb-mergeci/kustomization.yaml
=> Revert "feat/apps/prod/jenkins/post): prune resource in ns `jenkins-tidb-mergeci`"

apps/prod/jenkins/release/values-controller-plugins.yaml, apps/staging/jenkins/release/values-controller-plugins.yaml, charts/jenkins/values.yaml
=> Revert "chore(deps): update dependency git to v4.14.0"

apps/staging/jenkins/release/values-controller-plugins.yaml
=> Revert "chore(deps): update dependency pipeline-utility-steps to v2.14.0"

apps/prod/jenkins/release/values-JCasC.yaml, apps/staging/jenkins/release/values-JCasC.yaml
=> Revert "config(apps/jenkins): add codecov token for ticdc"

apps/prod/jenkins/release/values-JCasC.yaml, apps/prod/jenkins/release/values-controller-plugins.yaml, apps/prod/jenkins/release/values-controller.yaml
current version can not start for plugin failure
=> feat(apps/prod/jenkins/release): bump to 2.379

apps/prod/jenkins/release/values-JCasC.yaml, apps/staging/jenkins/release/values-JCasC.yaml
=> config(apps/jenkins): add codecov token for ticdc

apps/prod/jenkins/post/kustomization.yaml, apps/prod/jenkins/post/tiflow/kustomization.yaml, apps/prod/jenkins/post/tiflow/namespace.yaml
rename namespace for tiflow repo pipeline: from jenkins-ticdc to jenkins-tiflow
=> feat: rename namespace to jenkins-tiflow

apps/prod/jenkins/release/values-persistence.yaml
to 600GB
> current increased to 500GB manually
=> chore(apps/prod/jenkins/jrelease): increase jenkins home pvc size

apps/prod/jenkins/release/values-controller.yaml
- cpu doubled from 4 to 8.
- memory from 64GB to 80GB
=> chore(apps/prod/jenkins/release): increase jenkins cpu and memory requests

apps/staging/jenkins/release/values-controller-plugins.yaml
As title
Signed-off-by: lijie <lijie@pingcap.com>
=> improvement: use org repo rather than personal repo

apps/prod/greenhouse/release.yaml
- double cpu limits
- half memory since low usage.
- scale from 1 to 2
=> fix(apps/prod/greenhouse): increase resources for greenhouse deployment

apps/prod/jenkins/release/values-agent.yaml
=> feat(apps/prod/jenkins/release): increase jenkins pod cap

apps/prod/jenkins/release/values-agent.yaml, apps/staging/jenkins/release/values-agent.yaml
=> fix(apps/*/jenkins/release): fix inbound image with latest stable version

infrastructure/prod/rook-ceph/release-cluster.yaml, infrastructure/prod/rook-ceph/release-operator.yaml
=> Revert "feat(infrastructure/prod/rook-ceph): bump rook-ceph version to v1.10.0"

infrastructure/prod/rook-ceph/release-cluster.yaml
=> feat(infrastructure/prod/rook-ceph): add a host disk

infrastructure/prod/rook-ceph/release-cluster.yaml
- 3 hosts: node4, node5, node6
- one disk per node: /dev/nvme3n1
=> feat(infrastructure/prod/rook-ceph): add another three host disks

infrastructure/staging/rook-ceph/release-cluster.yaml, infrastructure/staging/rook-ceph/release-operator.yaml
=> feat(cluster/staging): bump rook-ceph to v1.10.7

README.md, infrastructure/prod/rook-ceph/release-cluster.yaml
- cluster-release-optional-values
=> refactor(infrastructure): delete useless secret

apps/staging/prow/post.yaml, apps/staging/prow/post/configs/config.yaml, apps/staging/prow/pre/kustomization.yaml, apps/staging/prow/pre/obc.yaml, apps/staging/prow/release.yaml, apps/staging/prow/release/kustomization.yaml, apps/staging/prow/release/release.yaml, charts/prow/Chart.yaml, charts/prow/config/default-prow-config.yaml.tpl, charts/prow/templates/_helpers.tpl, charts/prow/templates/components/crier/deployment.yaml, charts/prow/templates/components/deck/deployment.yaml, charts/prow/templates/components/status-reconciler/deployment.yaml, charts/prow/templates/components/tide/deployment.yaml, charts/prow/values.yaml
=> feat(charts/prow): add bucketname support

apps/staging/prow/release/release.yaml
=> fix(apps/staging/prow): disable needs-rebase

apps/staging/prow/release/release.yaml, charts/prow/Chart.yaml, charts/prow/templates/third-plugins/deployment.yaml, infrastructure/staging/monitoring/operator.yaml
=> fix(charts/prow): insert the default env

apps/staging/prow/release/release.yaml, charts/prow/Chart.yaml, charts/prow/templates/third-plugins/deployment.yaml, infrastructure/staging/monitoring/operator.yaml
=> Revert "fix(charts/prow): insert the default env"

apps/staging/prow/release/release.yaml, charts/prow/Chart.yaml, charts/prow/templates/third-plugins/service.yaml, charts/prow/values.yaml
This reverts commit aac685ff77a65290df8c5983963bce10ebb30eb9.
=> Revert "fix(charts/prow): insert the default env (#359)"

apps/staging/prow/post/github-rate-limit-exporter/kustomization.yaml, apps/staging/prow/post/github-rate-limit-exporter/release.yaml, apps/staging/prow/post/github-rate-limit-exporter/secret.yaml, apps/staging/prow/post/github-rate-limit-exporter/source.yaml
Deploy with implemention from https://github.com/kalgurn/github-rate-limits-prometheus-exporter
=> feature(apps/staging/prow/post): add github api rate limit metrics exporter

apps/dev/prow/post/configs/config.yaml, apps/dev/prow/release/release.yaml
=> chore(apps/dev/prow): bump tide image and update test configs

apps/staging/jenkins/release/values-controller-plugins.yaml
=> Revert "feat(staging/apps/jenkins): add jenkins plugin timestamper"

apps/staging/jenkins/release/values-controller-plugins.yaml
Resolve plugin version dependency issues
=> fix(staging/apps/jenkins): correct plugin dependency version

apps/prod/jenkins/pre/cronjobs.yaml, apps/prod/jenkins/pre/obc/obc.yaml
- and increase shrink frequency
=> chore(apps/prod/jenkins/pre): increase size for `ci-pipeline-cache`

apps/staging/prow/post/configs/config.yaml, apps/staging/prow/post/configs/plugins.yaml
=> chore(apps/staging/prow/post): delete pingcap-qe/ci repo in prow bot config

apps/prod/jenkins/post/tidb/files/bazel-prepare-in-container.sh
min between cpu cores and `total_bazel_mem_resource / default max memory per bazel task`
=> feat(apps/prod/jenkins/post/tidb): optimize the bazel `--jobs` option

apps/prod/jenkins/post/tidb/pvc-job.yaml, apps/staging/jenkins/post/tidb/pvc-job.yaml
=> feat(apps/prod/jenkins/post/tidb): update tidb data fresh jobs

apps/prod/jenkins/post/tidb/files/bazel-prepare-in-container.sh
=> Revert "feat(apps/prod/jenkins/post/tidb): optimize the bazel `--jobs` option"

apps/prod/greenhouse/release.yaml
=> chore(apps/prod/greenhouse): increase persistence size

infrastructure/prod/rook-ceph/release-cluster.yaml
=> chore(infrastructure): add a disk in node10 to ceph cluster

infrastructure/staging/rook-ceph/release-cluster.yaml
=> chore(infrastructure/staing/rook-ceph): update device disk osd config

infrastructure/staging/rook-ceph/release-cluster.yaml, infrastructure/staging/rook-ceph/release-operator.yaml
=> fix(infrastructure/staing/rook-ceph): fix ceph cluster

apps/dev/prow/post/configs/plugins.yaml
=> chore(apps/dev/prow/post/configs): update plugin config

apps/prod/jenkins/release/values-controller-plugins.yaml
Fix issue https://issues.jenkins.io/browse/JENKINS-70639?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20kubernetes-client-api-plugin
=> fix: fix jenkins k8s plugin version error

apps/staging/jenkins/release/values-controller-plugins.yaml
Related to jenkins k8s plugin issue https://issues.jenkins.io/browse/JENKINS-70639?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20kubernetes-client-api-plugin
=> fix(staging/jenkins): use the specify k8s client api plugin

infrastructure/prod/rook-ceph/release-cluster.yaml
=> chore(infrastructure/prod/rook-ceph): add 3 cluster nodes

infrastructure/prod/rook-ceph/release-cluster.yaml
=> chore(infrastructure/prod/rook-ceph): add 1 cluster nodes

apps/prod/greenhouse/release.yaml
=> chore(apps/prod/greenhouse): increase greenhouse data size to to 15Ti

apps/prod/jenkins/post/tidb/pvc.yaml
=> feat(apps/prod/jenkins/post/tidb): add deno-dir pvc

apps/staging/ats/release.yaml, apps/staging/jenkins/post/tidb/files/bazel, apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-call-jenkins.yaml
=> feat(apps/staging/ats): switch to nginx LB by url hash

README.md, clusters/staging/README.md
=> docs(cluster): update docs for clusters

apps/staging/ats/release.yaml
=> fix(apps/staging/ats): fix ingress paths

apps/staging/ats/release.yaml
=> fix(apps/staging/ats): fix nginx 413 too large error

apps/staging/ats/config-override/remap.config
=> chore(apps/staging/ats): update ats config override

apps/staging/ats/release.yaml, infrastructure/staging/rook-ceph/release-cluster.yaml
=> perf(stagings): increase read/write performance for ceph rbd

apps/dev/prow/release/release.yaml, apps/staging/prow/release/release.yaml
=> fix(apps/staging/prow/release): upgrade prow basic components

apps/dev/prow/post/configs/config.yaml
=> fix(apps/dev/prow/configs): update `lgtm` config to test the hacked `lgtm` built-in plugin

apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml, apps/staging/tekton/setup.yaml
=> feat(apps/staging/tekton): add deployments of tekton operator to health checks

apps/dev/prow/release/release.yaml, apps/staging/prow/release/release.yaml
=> fix(apps/staging/prow/release): upgrade prow hook component

apps/prod/jenkins-gitee/release/values-controller-plugins.yaml, apps/prod/jenkins-gitee/release/values-controller.yaml
=> fix(apps/prod/jenkins-gitee/release): bump version for jenkins server and fix plugin version conflicts

apps/prod/jenkins-gitee/release/values-controller.yaml
=> fix(apps/prod/jenkins-gitee/release): add init container to fix logs dir issue

apps/prod/jenkins-gitee/release/values-JCasC.yaml, apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
=> fix(apps/prod/jenkins-gitee/release): add readonly role and user

apps/prod/jenkins-gitee/release/values-JCasC.yaml
=> fix(apps/prod/jenkins-gitee/release): fix `additionalExistingSecrets`

apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
ref: https://plugins.jenkins.io/gitee/
=> feat(apps/prod/jenkins-gitee/release): add `gitee` plugin

apps/prod/jenkins-gitee/release/values-JCasC.yaml
=> fix(apps/prod/jenkins-gitee/release): fix job DSL dir path for seed job

apps/prod/jenkins-gitee/post/cronjob-go-caches.yaml, apps/prod/jenkins-gitee/post/pvc.yaml, apps/prod/jenkins-gitee/release/values-JCasC.yaml
no need to append prefix since it in seperate namespaces.
=> fix(apps/prod/jenkins-gitee/release): fix pvc names

apps/staging/harbor/release/release.yaml
=> fix(staging/harbor): use apps namespace

apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
=> feat(apps/prod/jenkins-gitee/release): add `ssh-agent` plugin

apps/prod/jenkins-gitee/release/values-JCasC.yaml
=> feat(apps/prod/jenkins-gitee/release): add gitee connection

apps/prod/jenkins/release/values-controller-plugins.yaml
=> feat(prod/jenkins): add plugin ssh-agent

apps/prod/jenkins/release/values-JCasC.yaml
=> config(apps/prod/jenkins): add some tokens

apps/prod/jenkins/release/values-controller-plugins.yaml, apps/prod/jenkins/release/values-controller.yaml
=> fix(apps/prod/jenkins/release): bump controller to v2.387.2

apps/staging/harbor/release/release.yaml
=> fix(staging/harbor): use 1.7.1 version of harbor helmchart

apps/staging/harbor/release/release.yaml
=> fix(staging/harbor): remove wrong valuses

apps/prod/tibuild/deployment.yaml, apps/prod/tibuild/ingress.yaml, apps/prod/tibuild/kustomization.yaml, apps/prod/tibuild/namespace.yaml, apps/prod/tibuild/service.yaml
deploy tibuild to kingsoft cloud
=> feat: deploy tibuild

apps/prod/jenkins-gitee/release/values-JCasC.yaml, apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
=> feat(apps/prod/jenkins-gitee): add `lock-resource` plugin and add cred for github repos

apps/staging/jenkins/release/values-controller-plugins.yaml
=> fix(apps/staging/jenkins/release): fix plugin conflicts

apps/dev/prow/release/release.yaml
=> fix(apps/dev/prow/release): fix port for chatgpt external plugin

apps/staging/prow/release/release.yaml
upgrade the release to fix it.
=> fix(apps/staging/prow/release): fix hmac token issue

apps/staging/prow/release/release.yaml
=> fix(apps/staging/prow/release): fix port for chatgpt external plugin

apps/staging/prow/post/configs/plugins.yaml
Config:
- add repository with external_plugins chatgpt;
=> chore(apps/staging/prow/post): enable chatgpt external plugin for `pingcap-qe/tirelease` repo

apps/staging/jenkins/release/values-controller-plugins.yaml
=> feat(staging/jenkins): add plugin ssh-agent

apps/gcp/prow/post/ci-jobs.yaml
=> fix(apps/gcp/prow/post): using new path for prow jobs.

README.md
=> Revert "Test for plugin"

apps/gcp/prow/post/post.yaml, apps/gcp/prow/release/release.yaml
=> fix(apps/gcp/prow/release): bump ti-* plugin image to v2.4.2

apps/gcp/prow/release/release.yaml
=> Revert "chore(apps/gcp/prow/release): update deployment for jenkins operator to skip report"

charts/prow/Chart.yaml, charts/prow/values.yaml
Comment out test job.
The display of testing tasks in the production environment is confusing. https://prow.tidb.net/?job=echo-test.
=> chore: comment out test job

apps/dev/prow/release/release.yaml
=> chore(apps/dev/prow/release): bump third party ti-community-* to v2.4.2

apps/staging/kustomization.yaml, apps/staging/namespace.yaml, apps/staging/sec-server/deployment.yaml, apps/staging/sec-server/kustomization.yaml, apps/staging/sec-server/rbac.yaml, apps/staging/sec-server/service.yaml, apps/staging/sec-service/kustomization.yaml, apps/staging/sec-service/namespace.yaml, apps/staging/sec-service/rbac.yaml, apps/staging/sec-service/redis/deployment.yaml, apps/staging/sec-service/redis/kustomization.yaml, apps/staging/sec-service/redis/service.yaml, apps/staging/sec-service/sec-agent/deployment.yaml, apps/staging/sec-service/sec-agent/kustomization.yaml, apps/staging/sec-service/sec-server/deployment.yaml, apps/staging/sec-service/sec-server/kustomization.yaml, apps/staging/sec-service/sec-server/service.yaml
Testing the security scanning process
=> feat(apps/staging/sec-server): Increased security scanning capabilities

apps/staging/kustomization.yaml, apps/staging/sec-service.yaml
make the security scan service effective.
=> feat(apps/staging/sec-server): deploy sec service

apps/staging/sec-service.yaml
=> fix(apps/staging/sec-server): fix substitute for kustomization sec-service

apps/staging/prow/post/configs/plugins.yaml, apps/staging/prow/release/release.yaml
- enable it on pingcap-qe/artifacts repo
=> feat(apps/staging/prow): upgrade to new chatgpt plugin

apps/staging/prow/release/release.yaml
=> fix(apps/staging/prow): fix chatgpt container args

apps/staging/prow/post/configs/config.yaml, apps/staging/prow/post/configs/kustomization.yaml, apps/staging/prow/post/configs/plugins.yaml, apps/staging/prow/post/configs/third-plugins/chatgpt/tasks.yaml, apps/staging/prow/post/configs/third-plugins/kustomization.yaml
=> feat(apps/staging/prow): add openai flow task config with gitOps

apps/staging/prow/post/configs/config.yaml
=> fix(apps/staging/prow): delete white space in yaml

apps/gcp/prow/pre/chatgpt/tasks.yaml, apps/gcp/prow/pre/kustomization.yaml, apps/gcp/prow/release/release.yaml
=> feat(apps/gcp/prow): add deployment for openai plugin

apps/staging/tekton/configs/pipelines/kaniko-build.yaml, apps/staging/tekton/setup/operator-config.yaml
=> feat(apps/staging/tekton): try to implement mutli arch image building

apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml, apps/staging/tekton/configs/cluster-tasks/codescan-security-prow.yaml, apps/staging/tekton/configs/cluster-tasks/codescan-security.yaml, apps/staging/tekton/configs/cluster-tasks/kustomization.yaml, apps/staging/tekton/configs/pipelines/codescan-security.yaml, apps/staging/tekton/configs/pipelines/kustomization.yaml
=> feat(apps/staging): add dogfooding codescan security tekton tasks

apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
=> fix(apps/staing/prow/post/configs/jobs): fix tekton job `codescan-security`

apps/staging/prow/release/release.yaml
=> fix(apps/gcp/prow): bump chatgpt plugin image to v20230505-46ce180

apps/staging/prow/release/release.yaml, charts/prow/values.yaml
=> fix(apps/staing/prow/release): fix needs-rebase external plugin pod's ports

apps/staging/buildfarm/configs/config.yaml
=> chore(apps/staging/buildfarm): build buildfarm config

apps/staging/buildfarm/kustomization.yaml
=> fix(apps/staging/buildfarm): add namespace for kustomization

apps/staging/buildfarm/configs/config.yaml
=> fix(apps/staging/buildfarm): fix config

apps/staging/tekton/configs/cluster-tasks/codescan-security-prow.yaml, apps/staging/tekton/configs/cluster-tasks/codescan-security.yaml
Depend on https://github.com/PingCAP-QE/ci/pull/2038
=> refactor(apps/staging/tekton/configs/cluster-tasks): update tasks for new design of security service

apps/prod/sec-service/sec-agent/deployment.yaml, apps/prod/sec-service/sec-server/deployment.yaml
=> fix: feat(apps/staging/sec-service): Update the image repository

apps/prod/jenkins/post/tidb/kustomization.yaml
It's should not be a k8s secret, we will migrate it to config map.
=> feat(apps/prod/jenkins/post/tidb): add cm `bazel-rc` at namespace `jenkins-tidb`

apps/gcp/prow/release/release.yaml
=> fix(apps/gcp/prow/release): switch to gpt4 engine

apps/prod/jenkins/post/kustomization.yaml, apps/prod/jenkins/post/tiflash-schrodinger/kustomization.yaml, apps/prod/jenkins/post/tiflash-schrodinger/namespace.yaml
add ns jenkins-tiflash-schrodinger.
=> feat(apps/prod/jenkins): add ns jenkins-tiflash-schrodinger

apps/prod/tekton/setup.yaml
=> fix(apps/prod/tekton): add annotations for namespaces

apps/prod/tekton/setup.yaml
=> fix(apps/prod/tekton): fix kustomization source path

apps/prod/tekton/configs.yaml
=> fix(apps/prod/tekton): add annotations for workspace namespace

apps/prod/tekton/setup/operator-config.yaml
=> fix(apps/prod/tekton): add default pod template to fix run on the hosts

apps/gcp/prow/release/release.yaml
=> feat(apps/gcp/prow/release): upgrade external plugin chatgpt

apps/prod/tekton/configs/pipelines/kustomization.yaml
=> feat(apps/gcp/tekton/configs/pipelines): add pipeline `kaniko-build`

apps/prod/buildbarn/release.yaml, charts/buildbarn/Chart.yaml, charts/buildbarn/templates/frontend/ingress.yaml, charts/buildbarn/templates/storage/statefulset.yaml, charts/buildbarn/values.yaml
=> fix(apps/charts/buildbarn): migrate ingress to frontend instead of sheculder

apps/prod/buildbarn/release.yaml
=> Revert "feat(apps/prod/buildbarn): switch pvc storageclass to ceph-block for storage statfulset"

infrastructure/staging/nginx/release.yaml
=> chore(staging): update nginx ingress svc node ports

infrastructure/prod/rook-ceph/release-cluster.yaml
=> refactor(infrastructure/prod/rook-ceph): replace node

infrastructure/prod/rook-ceph/release-operator.yaml
=> refactor(infrastructure/prod/rook-ceph): disable admission controller

infrastructure/prod/rook-ceph/release-cluster.yaml
=> refactor(infrastructure/prod/rook-ceph): replace 2 nodes

infrastructure/prod/rook-ceph/release-cluster.yaml
=> refactor(infrastructure/prod/rook-ceph): replace 7 nodes

infrastructure/prod/rook-ceph/release-cluster.yaml
=> refactor(infrastructure/prod/rook-ceph): delete node10

apps/prod/buildbarn/release.yaml
=> chore(apps/prod/buildbarn): disable head method

apps/prod/buildbarn/release.yaml
=> Revert "chore(apps/prod/buildbarn): disable head method"

apps/prod/buildbarn/release.yaml
=> Revert "Revert "chore(apps/prod/buildbarn): disable head method""

apps/prod/brc/kustomization.yaml, apps/prod/brc/pvc.yaml, apps/prod/brc/release.yaml, apps/prod/kustomization.yaml
=> feat(apps/prod/brc): init brc release

apps/prod/buildbarn/release.yaml
=> feat(apps/prod/buildbarn): readcache brc with buildbarn

apps/prod/buildbarn/release.yaml
=> feat(apps/prod/buildbarn): switch pvc to ceph-block type

clusters/gcp/flux-system/kustomization.yaml, clusters/gcp/flux-system/notification.yaml
=> feat(cluster/gcp): add alert notifies

apps/prod/jenkins/post/tidb/files/canary-bazel, apps/prod/jenkins/post/tidb/files/canary-bazel-prepare-in-container.sh, apps/prod/jenkins/post/tidb/kustomization.yaml
=> feat(apps/prod/jenkins/post/tidb): add canary files for configmap `bazel`

apps/prod/OWNERS
=> chore(apps/prod): update owners

.gitignore, apps/dev/prow/post/label-sync-cronjob.yaml, apps/dev/prow/pre.yaml, apps/dev/prow/pre/configs/kustomization.yaml, apps/dev/prow/pre/kustomization.yaml, apps/dev/prow/pre/secrets.yaml, apps/dev/prow/release/release.yaml
=> fix(apps/dev/prow): fix configmap names and add secret generation

apps/dev/prow/pre/secrets.yaml
=> fix(apps/dev/prow/pre): fix secrets.yaml

apps/dev/prow/pre/configs/kustomization.yaml, apps/dev/prow/release/release.yaml
=> fix(apps/dev/prow): fix for external plugins volumns

apps/dev/prow/release/release.yaml
=> fix(apps/dev/prow/release): fix plugin config cli options for ti-community-tars plugin

charts/prow/Chart.yaml, charts/prow/templates/components/crier/deployment.yaml, charts/prow/templates/components/deck/deployment.yaml, charts/prow/templates/components/status-reconciler/deployment.yaml, charts/prow/templates/components/tide/deployment.yaml, charts/prow/values.yaml
- rename key name in `values.yaml` from `.persistent.credential` to `.persistent.credentials`.
- refactor with template builtin function `default` for if/else logics.
=> refactor(charts/prow): refactor prow persistent credentials

apps/dev/prow/pre/secrets.yaml, apps/dev/prow/release/release.yaml
=> feat(apps/dev/prow): add gcs credential secret and use it in release

apps/gcp/kustomization.yaml, apps/gcp/prow-crd.yaml, apps/gcp/prow/kustomization.yaml, apps/gcp/prow/post/kustomization.yaml, apps/gcp/prow/pre.yaml, apps/gcp/prow/pre/kustomization.yaml, apps/gcp/prow/pre/prow-configs.yaml, apps/gcp/prow/pre/prow-jobs.yaml, apps/gcp/prow/pre/secrets.yaml, apps/gcp/prow/release.yaml, apps/gcp/prow/release/gce-ingress.yaml, apps/gcp/prow/release/release.yaml
=> refactor(apps/gcp/prow): deploy configmap and secret before helm release

apps/gcp/prow/release/release.yaml
=> Revert "Revert "chore(apps/prod/prow/release): bump hook image to `ticommunityinfra/hook:v20230608-bd4b41b`""

apps/dev/prow-crd.yaml, apps/dev/prow/release/release.yaml, apps/gcp/prow-crd.yaml, apps/staging/prow-crd.yaml
=> feat(apps/dev/prow/release): bump image for hook component

.github/workflows/test-data/prow/ct-values.yaml, charts/prow/Chart.yaml, charts/prow/templates/components/deck/deployment.yaml, charts/prow/templates/components/ghproxy/deployment.yaml, charts/prow/templates/components/hook/deployment.yaml, charts/prow/templates/components/horologium/deployment.yaml, charts/prow/templates/components/tide/deployment.yaml, charts/prow/templates/third-plugins/deployment.yaml, charts/prow/values.yaml
- hook component
- external plugins
=> feat(charts/prow): add additional env supports

apps/dev/prow/release/release.yaml, clusters/dev/flux-system/kustomization.yaml, clusters/dev/flux-system/notification.yaml
=> feat(clusters/dev): add alert notifies

apps/dev/prow/release/release.yaml
try to avoid low performance of helm action
=> feat(apps/dev/prow/release): increase interval and timeout

apps/gcp/prow/release/release.yaml
=> feat(apps/gcp/prow/release): increase interval and timeout

apps/gcp/prow/post/cronjobs-community.yaml, apps/gcp/prow/post/kustomization.yaml
=> fix(apps/gcp/prow): add post cron jobs

apps/gcp/prow/release/release.yaml
- pingcap/tiflow
- pingcap/docs
- pingcap/docs-cn
- pingcap/docs-tidb-operator
=> chore(apps/gcp/prow): add lgtm sticky for repos

apps/prod/buildbarn/release.yaml
=> fix(apps/prod/buildbarn): fix pvc size for storage shards

apps/gcp/prow/release/release.yaml
=> chore(apps/gcp/prow): add lgtm sticky repos

apps/dev/prow/release/release.yaml
=> chore(apps/dev/prow): bump prow chart release to v0.9.3

apps/gcp/prow/pre/chatgpt/tasks.yaml
=> chore(apps/gcp/prow/pre/chatgpt): add `default` task for document repos

apps/gcp/prow/pre/chatgpt/tasks.yaml
=> chore(apps/gcp/prow/pre/chatgpt): increase `max_response_tokens` for docs repos

apps/gcp/prow/pre/chatgpt/tasks.yaml
Use a shorter prompt for better review results.
=> update the default user prompt for docs repo

apps/prod/tekton/configs.yaml, apps/prod/tekton/configs/triggers/event-listener.yaml, apps/prod/tekton/configs/triggers/ingress-event-listener.yaml, apps/prod/tekton/configs/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/public.yaml, apps/prod/tekton/setup.yaml
=> chore(apps/prod/tekton): add ingress for event listenser

apps/dev/prow/release/release.yaml, apps/gcp/prow/pre/chatgpt/tasks.yaml, apps/gcp/prow/release/release.yaml
=> feature(apps/prod/prow): bump chatgpt to v20230621-df5abce

apps/prod/buildbarn/release.yaml, charts/buildbarn/values.yaml
Also fix comments in file: `charts/buildbarn/values.yaml`.
=> feature(apps/prod/buildbarn): add ingress for buildbarn services

apps/prod/buildbarn/release.yaml, charts/buildbarn/Chart.yaml, charts/buildbarn/templates/frontend/ingress.yaml
=> fix(charts/buildbarn): fix ingress for frontend component

apps/prod/buildbarn/release.yaml
=> feature(apps/prod/buildbarn): use ingress class name

apps/dev/prow/release/release.yaml
=>  feature(apps/dev/prow/prow/release): bump hook's image tag to `v20230627-6810132`

apps/gcp/prow/release/release.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2186
=> fix(apps/gc/prow/release): enable report for jenkins-operator

charts/prow/Chart.yaml, charts/prow/templates/components/crier/deployment.yaml, charts/prow/templates/components/deck/deployment.yaml, charts/prow/templates/components/hook/deployment.yaml, charts/prow/templates/components/horologium/deployment.yaml, charts/prow/templates/components/jenkins-operator/deployment.yaml, charts/prow/templates/components/prow-controller-manager/deployment.yaml, charts/prow/templates/components/sinker/deployment.yaml, charts/prow/templates/components/status-reconciler/deployment.yaml, charts/prow/templates/components/tide/deployment.yaml, charts/prow/values.yaml
=> feat(charts/prow): add kubeconfig secret support

apps/dev/prow/release/release.yaml
=>  feature(apps/dev/prow/prow/release): bump release to `0.9.4`

apps/gcp/prow/release/release.yaml
=>  feature(apps/gcp/prow/prow/release): add `--kubeconfig` options to components

apps/gcp/prow/pre/kustomization.yaml, apps/gcp/prow/pre/secrets-test-pods.yaml
=> fix(apps/gcp/prow/release): add gcs credential to `prow-test-pods` namespace

apps/prod/kustomization.yaml, apps/prod/prow-worker/kustomization.yaml, apps/prod/prow-worker/namespace.yaml, apps/prod/prow-worker/pvc.yaml
=> feat(apps/prod/prow-worker): setup prow job's pod namespace

apps/dev/prow/release/release.yaml
Ref https://github.com/ti-community-infra/test-infra/pull/35
=> fix(apps/dev/prow/release): bump tide image

apps/dev/prow/release/release.yaml
=> fix(apps/dev/prow/release): bump hook image

apps/prod/jenkins-beta/release/values-controller.yaml
add node affinity to ensure that the service is deployed on the desired nodes.
=> feat(apps/prod/jenkins-beta): add node affinity

apps/gcp/prow/release/release.yaml
=> Revert "Revert "fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`""

apps/prod/tekton/configs/pipelines/pipeline1.yaml
=> fix(apps/prod/tekton/configs/pipelines): fix demo pipeline

infrastructure/_base/sources/helm-repo-nfs-server-provisioner.yaml, infrastructure/_base/sources/kustomization.yaml, infrastructure/prod/nfs-pvc-provisioner/kustomization.yaml, infrastructure/prod/nfs-pvc-provisioner/namespace.yaml, infrastructure/prod/nfs-pvc-provisioner/release.yaml
=> feat(infrastructure): add nfs PVC provisioner

apps/_base/sources/helm-repo-ee-apps.yaml, apps/prod/cloudevents-server/config-configmap.yaml, apps/prod/cloudevents-server/data-pvc.yaml, apps/prod/cloudevents-server/kustomization.yaml, apps/prod/cloudevents-server/release.yaml
=> feat(apps/prod): add cloudevents-server instance

apps/prod/jenkins-beta/release/values-controller-plugins.yaml
Update with upstream to fix security
=> chore(apps/prod/jenkins-beta/release): bump plugin `bfa`

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/NOTES.txt, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/config.yaml, charts/jenkins/templates/home-pvc.yaml, charts/jenkins/templates/jenkins-agent-svc.yaml, charts/jenkins/templates/jenkins-backup-cronjob.yaml, charts/jenkins/templates/jenkins-controller-ingress.yaml, charts/jenkins/templates/jenkins-controller-podmonitor.yaml, charts/jenkins/templates/jenkins-controller-servicemonitor.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/jenkins-controller-svc.yaml, charts/jenkins/templates/secret-https-jks.yaml, charts/jenkins/templates/service-account-agent.yaml, charts/jenkins/templates/service-account.yaml, charts/jenkins/templates/tests/jenkins-test.yaml, charts/jenkins/values.yaml
=> feat(charts/jenkins): update with upstream

apps/prod/jenkins-beta/release/values-controller.yaml
fix CVEs, ref: https://www.jenkins.io/security/advisories/
=> fix(apps/prod/jenkins-beta/release): bump to v2.414.3

apps/prod/jenkins/release/values-controller-plugins.yaml
Update with upstream to fix security issues.
Tests:
=> fix(apps/prod/jenkins/release): bump `bfa` plugin

apps/prod/jenkins/release/values-controller-plugins.yaml, apps/prod/jenkins/release/values-controller.yaml, apps/staging/jenkins/release/values-controller.yaml
=> fix(apps/prod/jenkins/release): bump jenkins to v2.414.3

apps/dev/tekton/kustomization.yaml
=> feature(apps/dev/tekton): enable external https service with http routes

apps/prod/tekton/configs/triggers/bindings/github-branch-push.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/push-build.yaml, apps/prod/tekton/configs/triggers/test.http
=> feat(apps/prod/tekton/configs/triggers): fix trigger resources

apps/prod/tekton/setup/operator-config.yaml, apps/prod/tekton/setup/operator-release.yaml
=> feat(apps/prod/tekton/setup): bump tekton-operator to v0.56.0

apps/prod/tekton/configs/triggers/templates/pingcap/tidb/push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/push.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/push.yaml, apps/prod/tekton/configs/triggers/templates/tikv/tikv/push.yaml
- tidb: 10GB
- pd: 2GB
- tikv: 10GB
- tiflow: 10GB
- tiflash: 10GB
=> feat(apps/prod/tekton/configs/triggers/templates): increase size for `source` workspace

apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
=> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-build-binaries`

apps/prod/tekton/configs/pipelines/push-build-package.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/push.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/push.yaml
currently on push on master events.
=> feat(apps/prod/tekton/configs): add build flow for `pingcap/advanced-statefulset`

apps/prod/tekton/configs/pipelines/push-build-package.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tidb/push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/push.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/push.yaml, apps/prod/tekton/configs/triggers/templates/tikv/tikv/push.yaml, apps/prod/tekton/configs/triggers/test.http
=> fix(apps/prod/tekton/configs): fix tiflash pipelineRun builder images

apps/prod/tekton/configs/triggers/bindings/harbor-image-push.yaml, apps/prod/tekton/configs/triggers/bindings/kustomization.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/image-push.yaml, apps/prod/tekton/configs/triggers/test.http, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/image-push.yaml
Firstly deploy it on `pingcap/advance-statefulset` repo.
=> feat(apps/prod/tekton/configs): support image push events

apps/prod/tekton/configs/pipelines/auto-compose-multi-arch-image.yaml, apps/prod/tekton/configs/pipelines/kustomization.yaml, apps/prod/tekton/configs/tasks/gen-build-binaries-scripts.yaml, apps/prod/tekton/configs/tasks/gen-build-images-scripts.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/multi-arch-image-pre-collect.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/tasks/run-build-binaries-scripts.yaml, apps/prod/tekton/configs/triggers/bindings/harbor-image-push.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/image-push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/push.yaml, apps/prod/tekton/configs/triggers/test.http, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/image-push.yaml
=> feat(apps/prod/tekton/configs): support tag multi-arch image

apps/prod/tekton/configs/pipelines/auto-compose-multi-arch-image.yaml, apps/prod/tekton/configs/pipelines/push-build-package.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/image-push.yaml
Now it's basd on events, but we can easy run it with some params.
=> feat(apps/prod/tekton/configs): support auto compose multi arch images

apps/prod/jenkins-beta/release/values-controller.yaml
Add renovate to auto bump jenkins-beta image tag.
=> feat(apps/prod/jenkins-beta): add renovate to auto bump jenkins-beta image tag

apps/prod/tibuild/deployment.yaml
Why:
- use new rocky image for fips image
Testing:
- unit test
- local rest api tested
=> feat: fips feature for tibuild

apps/prod/tekton/configs/pipelines/kustomization.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tidb/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/tikv/build.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
=> fix(apps/prod/tekton/configs): enable git repo tag triggers

apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/build.yaml
=> fix(apps/prod/tekton/configs): fix tiflash trigger template name

apps/gcp/tekton-dev/configs/triggers/event-listener.yaml, apps/gcp/tekton-dev/ingress/http-routes.yaml, apps/prod/tekton/configs/triggers/bindings/ce-context.yaml, apps/prod/tekton/configs/triggers/bindings/kustomization.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener-internal.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener-public.yaml, apps/prod/tekton/configs/triggers/event-listeners/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/build.yaml, apps/prod/tekton/configs/triggers/test.http, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-push.yaml, apps/prod/tekton/ingress/ingress-event-listener.yaml, apps/staging/prow/post/configs/plugins.yaml
add listener and trigger for tibuild
=> feat(apps/prod/tekton): support internal triggers

apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/tasks/run-build-images-scripts.yaml
=> fix(apps/prod/tekton/configs/tasks): fix tasks

apps/prod/tekton/configs/triggers/bindings/ce-context.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener-internal.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/advanced-statefulset/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tidb/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/tikv/build.yaml, apps/prod/tekton/configs/triggers/test.http, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-push.yaml
- pd
- tikv
- tiflash
- tidb
- tiflow
- advanced-statefulset
=> feat(apps/prod/tekton): support internal triggers for components

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/tasks/boskos-acquire.yaml
=> feat(apps/prod/tekton/configs): add timeout in acquire mac builder resource task

apps/prod/tekton/setup/operator-release.yaml
=> Revert "chore(apps/prod/tekton/setup): bump tekton operator to v0.64.0"

apps/prod/tekton/setup/operator-release.yaml
=> Revert "chore(apps/prod/tekton/setup): bump tekton operator to v0.65.0"

apps/prod/tekton/setup/operator-release.yaml
=> Revert "chore(apps/prod/tekton/setup): bump tekton operator to v0.63.0"

apps/prod/tekton/setup/operator-release.yaml
=> Revert "chore(apps/prod/tekton/setup): bump tekton operator to v0.62.0"

apps/prod/tekton/setup.yaml, apps/prod/tekton/setup/operator-release.yaml
=> chore(apps/prod/tekton/setup): bump tekton operator to v0.65.1

apps/prod/tekton/setup.yaml, apps/prod/tekton/setup/operator-release.yaml
=> Revert "chore(apps/prod/tekton/setup): bump tekton operator to v0.65.1"

apps/prod/tekton/setup/operator-release.yaml
=> chore(apps/prod/tekton/setup): bump tekton operator to v0.61.0

clusters/prod/flux-system/gotk-sync.yaml
=> chore(clusters/prod): make gitops git source updating fast

apps/prod/kustomization.yaml, apps/prod/triggermesh/kustomization.yaml, apps/prod/triggermesh/triggermesh.yaml
Ref: https://github.com/triggermesh/triggermesh
=> chore(apps/prod): add triggermesh service

apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
=> feat(apps/prod/tekton/configs): add pipeline results for pingcap build

apps/prod/tekton/configs/tasks/boskos-acquire.yaml, apps/prod/tekton/configs/tasks/boskos-release.yaml
=> Revert "chore(deps): update docker.io/lachlanevenson/k8s-kubectl docker digest to be98414"

apps/prod/dl/kustomization.yaml, apps/prod/dl/release.yaml, apps/prod/kustomization.yaml
=> feat(apps/prod/dl): init deploy

apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
Add this part:  "master-00595b4" => "master"
=> feat(apps/prod/tekton/configs/task): implement merge image tags

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tidb/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflash/build.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/tiflow/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/pd/build.yaml, apps/prod/tekton/configs/triggers/templates/tikv/tikv/build.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
=> feat(apps/prod/tekton/configs/triggers): enable trigger for fips feature branches

apps/prod/tekton/configs/triggers/templates/_/build-component.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/_/git-push-on-fips-branches.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
Make it not affect trunk building
=> refactor(apps/prod/tekton/configs/triggers): make fips standalone

apps/prod/jenkins-beta/release/values-controller-plugins.yaml, apps/prod/jenkins/release/values-controller-plugins.yaml, apps/staging/jenkins/release/values-controller-plugins.yaml
=> Revert "chore(deps): update dependency blueocean to v1.27.9"

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/pingcap-get-release-version.yaml
=> refactor(apps/prod/tekton/configs/tasks): extract the task and make execlude the date tags

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
=> fix(apps/prod/tekton/configs/tasks): fix task results

apps/prod/tekton/setup/operator-config.yaml
=> chore(apps/prod/tekton/setup): increase pruner keep size to 1000

apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml, apps/prod/tekton/configs/triggers/templates/_/artifact-push.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/tests/dev-build.http, apps/prod/tekton/configs/triggers/tests/harbor.http, apps/prod/tekton/configs/triggers/tests/test.http, apps/prod/tekton/configs/triggers/triggers/_/artifact-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-push.yaml
tekton event listener will sink the webhook events from hub.pingcap.net.
=> feat(apps/prod/tekton/configs): auto release tiup pkg to staging tiup mirror

apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-push.yaml
=> feat(apps/prod/tekton/configs): prepare switch nightly build for tiproxy

apps/prod/jenkins/release/values-JCasC.yaml, apps/prod/jenkins/release/values-controller.yaml
=> fix(apps/prod/jenkins/release): fix jenkins log dir

apps/prod/jenkins/release/values-JCasC.yaml, apps/prod/jenkins/release/values-controller.yaml
=> Revert "fix(apps/prod/jenkins/release): fix jenkins log dir"

apps/prod/jenkins/release/values-JCasC.yaml
=> Revert "disable global plugins jscsc"

apps/prod/jenkins/release/values-JCasC.yaml
=> Revert "Revert "disable global plugins jscsc""

apps/prod/cloudevents-server/release.yaml
=> chore(apps/prod/cloudevents-server): bump image tag to `b33e8e2`

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-push.yaml
=> feat(apps/prod/tekton/configs/triggers/pingcap/tidb): add trigger build with enterpriseprofile

apps/prod/jenkins-beta/release/values-controller-plugins.yaml
=> fix(apps/prod/jenkins-beta/release): fix lackness plugin

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml, apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml, apps/prod/tekton/configs/triggers/triggers/_/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs): fix task and trigger for tiup publishing

apps/prod/tekton/configs/tasks/add-image-major-tag.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/_/image-push.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
when `master` or `main` tag pushed, it will add `nightly` tag.
when no-pre semver tag added, it will add `latest` when the version is higher than the exist no-pre semver tags.
=> feat(apps/prod/tekton/configs): auto add `nightly` and `latest` tag for image

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
disable it before it be fixed.
=> fix(apps/prod/tekton/configs/triggers): currently we can not support the private repo on build

apps/prod/tekton/configs/triggers/tests/test.http, apps/prod/tekton/configs/triggers/triggers/_/git-push-on-trunk-branches.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
- release profile
- enterprise profile
=> fix(apps/prod/tekton/configs/triggers): fix trigger for tidb

apps/prod/tekton/configs/triggers/tests/test-6.5-fips.http
=> chore(apps/prod/tekton/configs/triggers/tests): update http test data

apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/restore-cache-with-ks3.yaml, apps/prod/tekton/configs/tasks/save-cache-with-ks3.yaml
=> feat(apps/prod/tekton/configs): add cache save and restore tasks with ks3

apps/prod/boskos/boskos-resources.yaml
=> feat(apps/prod/boskos): add mac resources

apps/prod/tekton/configs/triggers/bindings/github-branch-create.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/sync-owners-for-hotfix-branch.yaml
=> feat(apps/prod/tekton/configs/triggers/bindings): fix `github-branch-create` binding

apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/pingcap-auto-add-image-major-tag.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs): rename task `add-image-major-tag` to `pingcap-auto-add-image-major-tag`

apps/prod/tekton/configs/tasks/hotfix/create-pr-to-fix-gomod.yaml
=> fix(apps/prod/tekton/tasks): fix steps for `create-pr-to-fix-gomod` task

apps/prod/cloudevents-server/release.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/68
=> fix(apps/prod/cloudevents-server): bump image tag to `8e81412`

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml, apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml, apps/prod/tekton/configs/triggers/tests/test.http
=> fix(deps): bump tiup tool to v1.14.1

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-push.yaml
=> feat: add ng-monitoring trigger

apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml, apps/prod/tekton/configs/triggers/triggers/_/artifact-push-on-harbor.yaml
fix the problem that tag with dup tags.
=> fix(apps/prod/tekton/configs/tasks): fix task `multi-arch-image-collect`

apps/prod/tekton/configs/tasks/hotfix/create-pr-to-fix-gomod.yaml
avoid failure when the project is not bazel project
=> fix(apps/prod/tekton/configs/tasks): fix task create-pr-to-fix-gomod-for-hotfix

apps/prod/tekton/configs/rbac/kustomization.yaml, apps/prod/tekton/configs/rbac/releaser.yaml, apps/prod/tekton/configs/tasks/crane-copy.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor-tiproxy.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
=> feat(pingcap/tiproxy): auto publish tiproxy image to dockerhub

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow-operator/test.http
- need trigger tiflow-operator at nightly
=> feat: add tiflow-operator nightly trigger

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
=> feat(apps/pfod/tekton/configs/triggers): enable enterprise build for tidb on feature release branches

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml
=> fix(apps/prod/tekton/configs/pipelines): add results for `pingcap-build-package-darwin`

apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/triggers): fix triggers for image pushing

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/test.http
- tidb-ctl only build for master branch
=> feat: add tidb-ctl trigger

.github/renovate.json, apps/prod/cloudevents-server/release.yaml
=> feat(apps/prod/cloudevents-server): bump image tag to `0f5542f`

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/_/ctl/harbor.http
CEL do not support index with `-1` like golang.
=> fix(apps/prod/tekton/configs/triggers): fix trigger for `ctl` building

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
Prepare for multi-repo checkouts
=> fix(apps/prod/tekton/configs/pipelines): checkout with to a folder and make branch checkout able

apps/prod/tibuild/deployment.yaml
Why:
- https://github.com/PingCAP-QE/ee-apps/pull/74
=> chore: update tibuild for github client

apps/prod/tibuild/deployment.yaml
- https://github.com/PingCAP-QE/ee-apps/pull/78
=> chore: upgrade tibuild

apps/prod/jenkins/release/values-JCasC.yaml
*  add docs-cn token.
*  add tiproxy codecov token
=> feat: add docs-cn token

apps/prod/jenkins/release/values-JCasC.yaml
=> Revert "feat: add docs-cn token"

apps/prod/jenkins/release/values-JCasC.yaml
=> Revert "Update values-JCasC.yaml"

apps/prod/jenkins-beta/release/values-JCasC.yaml
add some token on jenkins-beta for test.
=> feat(apps/prod/jenkins-beta): add some token on jenkins-beta for test

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml
=> feat(apps/prod/tekton/configs/triggers/pingcap/tidb): support trigger buildings with enterprise profile

apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
avoid to combine images with different profiles.
=> feat(apps/prod/tekton/configs/tasks): fix task `multi-arch-image-collect`

apps/prod/cloudevents-server/release.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/79
=> chore(apps/prod/cloudevents-server): bump image tag to `403acb5`

apps/prod/tibuild/deployment.yaml
Why:
- ref https://github.com/PingCAP-QE/ee-apps/pull/80
=> chore: update tibuild

apps/prod/cloudevents-server/release.yaml
Feature ref: https://github.com/PingCAP-QE/ee-apps/pull/86
=> feat(apps/prod/cloudevents-server): bump image tag to `v20240228-3-g051c1fd`

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(pingcap/ctl): do not trigger builds for darwin platforms

apps/gcp/prow/release/release.yaml
bump to tag `v20240301-09ad8bf`
=> chores(apps/gcp/prow): bump image for hook

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
=> feat(apps/prod/tekton/configs/triggers): support trigger buildings with debug profile

apps/prod/tekton/configs/tasks/gen-build-binaries-scripts.yaml, apps/prod/tekton/configs/tasks/gen-build-images-scripts.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/tasks/pingcap-get-builder-image.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
Ref: https://github.com/PingCAP-QE/artifacts/pull/264
=> fix(apps/prod/tekton/configs): adjust profile param value from "debug" to "failpoint"

apps/prod/boskos/boskos-resources.yaml
Reverts PingCAP-QE/ee-ops#1014
=> Revert "Update boskos-resources.yaml"

apps/prod/tekton/configs/tasks/pingcap-git-clone-ext.yaml
=> feat(apps/prod/tekton/configs/tasks): fix task `pingcap-git-clone-ext`

apps/prod/tekton/configs/tasks/pingcap-get-release-version.yaml
=> refactor(apps/prod/tekton/configs/tasks): auto bump the patch version for branch checkout

apps/prod/tekton/configs/tasks/pingcap-get-release-version.yaml
Reverts PingCAP-QE/ee-ops#1016
=> Revert "refactor(apps/prod/tekton/configs/tasks): auto bump the patch version for branch checkout"

apps/prod/tekton/configs/tasks/pingcap-get-release-version.yaml
Reverts PingCAP-QE/ee-ops#1018
=> Revert "Revert "refactor(apps/prod/tekton/configs/tasks): auto bump the patch version for branch checkout""

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
=> opt(apps/prod/tekton/configs/tasks): set locale for darwin builder

apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml
add `check` step in task `pingcap-compose-offline-pkgs`
=> opt(apps/prod/tekton/configs/tasks): update offline tiup pkg task

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
Ref: https://github.com/PingCAP-QE/artifacts/pull/274
=> chore(apps/prod/tekton/configs/tasks): update task `publish-tiup-from-oci-artifact`

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
=> chore(apps/prod/tekton/configs/tasks): add tag for release branches when building

apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
Add step `add-more-tags`
Ref: https://github.com/PingCAP-QE/artifacts/pull/275
=> feat(apps/prod/tekton/configs/tasks): update task `pingcap-build-images`

apps/prod/tekton/configs/tasks/pingcap-get-release-version.yaml, apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml
=> chore(apps/prod/tekton/configs/tasks): add debug output message

apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
Fix the image tag step
Ref https://github.com/PingCAP-QE/artifacts/pull/277
=> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-build-images`

apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
Add triggerings when RC image pushed, also include other profiles.
=> chore(apps/prod/tekton/configs/triggers): update trigger `multi-arch-image-push-on-harbor-branch-tags`

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-push.yaml
=> chore(apps/prod/tekton/configs/triggers): enable trigger for release-8.0 branch

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml
=> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-get-set-release-version`

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-create-branch.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-branch.yaml
=> chore(apps/prod/tekton/configs/triggers): support first patch version rc build

apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-push.yaml
=> fix(apps/prod/tekton/configs/triggers): fix trigger branches

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml
=> fix(apps/prod/tekton/configs/triggers): fix version set

apps/prod/dl/release.yaml
=> fix(apps/prod/dl): update ingress domain

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version.yaml
tidb-dashboard has the dirty tag will affect the logic, like: v8.0.0-abefa123
we firstly delete them.
=> fix(apps/prod/tekton/configs/tasks): add delete dirty tag step

apps/prod/tekton/configs/tasks/pingcap-build-images.yaml, apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/tasks): support for ctl darwin targets

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
add other trigger source oci repos
=> fix(apps/prod/tekton/configs/triggers): fix trigger for ctl

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
Reverts PingCAP-QE/ee-ops#1043
=> Revert "fix(apps/prod/tekton/configs/triggers): fix trigger for ctl"

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/triggers): fix triggers for ctl release branches

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
Reverts PingCAP-QE/ee-ops#1044
=> Revert "Revert "fix(apps/prod/tekton/configs/triggers): fix trigger for ctl""

apps/prod/tekton/setup/pipeline/release.yaml, apps/prod/tekton/setup/triggers/release.yaml
=> fix(apps/prod/tekton/setup): update config map

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/triggers): fix trigger params for ctl pkg

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package.yaml
=> fix(apps/prod/tekton/configs/pipelines): use checkout result as commit sha to downstream tasks

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
=> fix(apps/prod/tekton/configs/tasks): retry pushing to OCI registry

apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component.yaml, apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/triggers): add `profile` value into the pipeline run names

apps/prod/tekton/configs/triggers/tests/test-github-events.ts
support event types:
- github push event
- github tag create event
=> test(apps/prod/tekton/configs/triggers): add deno script to send github events

apps/prod/tekton/setup/cronjobs/kustomization.yaml, apps/prod/tekton/setup/cronjobs/tekton-resource-pruner.yaml, apps/prod/tekton/setup/kustomization.yaml
=> test(apps/prod/tekton/setup): add prune cron job

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
=> chore(apps/prod/tekton/configs/triggers): disable github tag create triggers

apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
We will upgrade it v0.24.0 later.
=> test(apps/prod/tekton/setup/triggers): upgrade triggers component to v0.21.0

apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
=> fix(apps/prod/tekton/setup/triggers): bump triggers to v0.22.0

apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
=> fix(apps/prod/tekton/setup/triggers): bump triggers to v0.22.1

apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
=> fix(apps/prod/tekton/setup/triggers): bump to v0.24.1

apps/prod/tekton/setup/dashboard/release.yaml
=> fix(apps/prod/tekton/setup/dashboard): bump to v0.29.2

apps/prod/tekton/setup/dashboard/release.yaml
=> fix(apps/prod/tekton/setup/dashboard): bump dashboard to v0.31.0

apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml
=> fix(apps/prod/tekton/configs/tasks): avoid repeated tag in composing multi-arch image

apps/prod/tekton/configs/tasks/pingcap-compose-offline-pkgs.yaml, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
=> refactor(apps/prod/tekton/configs/tasks): refactor the offline pkg task

apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml
currently it's only enabled the standalone releasing repos.
=> fix(apps/prod/tekton/configs/triggers): fix git tag triggers

apps/prod/cloudevents-server/release.yaml
Introduce the feature: https://github.com/PingCAP-QE/artifacts/pull/290
=> feat(apps/prod/cloudevents-server): bump image to `v20240228-17-g0345db4`

apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml
Reverts PingCAP-QE/ee-ops#1071
=> Revert "fix(apps/prod/tekton/configs/triggers): fix git tag triggers"

apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/advanced-statefulset/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ng-monitoring/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-ctl/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-tools/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiproxy/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/fake-git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/tikv/git-create-tag.yaml
Reverts PingCAP-QE/ee-ops#1073
=> Revert "Revert "fix(apps/prod/tekton/configs/triggers): fix git tag triggers""

apps/prod/tekton/configs/tasks/multi-arch-image-collect.yaml, apps/prod/tekton/configs/triggers/tests/test-github-events.ts, apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
=> feat(apps/prod/tekton/configs/tasks): strict list multi arch images

apps/prod/tekton/configs/tasks/boskos-acquire.yaml
=> fix(apps/prod/tekton/configs/tasks): increase mac resource acquire stability

apps/prod/tekton/configs/pipelines/kustomization.yaml, apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml, apps/prod/tekton/configs/tasks/pingcap-upload-offline-packages.yaml
put the shell script in to ci.git and call it.
=> feat(apps/prod/tekton/configs/pipelines): update pipeline `pingcap-release-ga`

apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml, apps/prod/tekton/configs/tasks/pingcap-upload-offline-packages.yaml
=> feat(apps/prod/tekton/configs/tags): avoid uploading with the `*-pre-*` name

apps/prod/tekton/configs/pvcs/kustomization.yaml, apps/prod/tekton/configs/pvcs/tiup-locks.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml, apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml
=> fix(apps/prod/tekton/configs): use RWO pvc to lock in tiup uploading

apps/prod/tekton/configs/triggers/triggers/_/image-push-on-harbor.yaml
=> tests(apps/prod/tekton/configs/triggers): add trigger to deliver GA images

.ci/OWNERS, OWNERS, apps/OWNERS, apps/prod/OWNERS, charts/OWNERS, clusters/OWNERS, infrastructure/OWNERS
lijie0123 became an emeritus reviewer
=> chore: update prow OWNERS files

apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml, apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
- `create-pr-to-add-release-anchor-commit` to solve the lazy active repos in automatic releasing flows.
- `create-pr-to-bump-tikv-version` bump tikv pkg version automatic.
=> feat(apps/prod/tekton/configs/tasks): add release ops tasks

apps/prod/tekton/configs/tasks/hotfix/create-pr-to-sync-owners.yaml, apps/prod/tekton/configs/tasks/pingcap-deliver-image.yaml, apps/prod/tekton/configs/triggers/templates/_/image-push.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/sync-owners-for-hotfix-branch.yaml
=> fix(apps/prod/tekton/configs): upgrade deno image to support run on arm64 nodes

apps/prod/tekton/configs/tasks/release/create-pr-to-add-release-anchor-commit.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/templates/pingcap/bump-placeholder-version-in-readme.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-binlog/git-create-branch.yaml
=> feat(apps/prod/tekton/configs/triggers): enable trigger for tidb-binlog to add version placeholder commits

apps/prod/jenkins/pre/cronjobs.yaml, apps/prod/jenkins/pre/obc/obc.yaml, apps/staging/jenkins/pre/obc/cronjobs.yaml
=> chore(apps/prod/jenkins/pre): increase OBC size for `ci-pipeline-cache`

apps/prod/boskos/boskos-resources.yaml
=> chore(apps/prod/boskos): delete the slow darwin runner

apps/gcp/prow/release/release.yaml
Reverts PingCAP-QE/ee-ops#1091
=> Revert "config(apps/prow): update prow statusreconciler"

apps/gcp/prow/release/release.yaml
Reverts PingCAP-QE/ee-ops#1092
=> config(apps/prow): update prow statusreconciler

apps/prod/git-cdn/release.yaml
=> opt(apps/prod/git-cdn): tuning server config to save more bandwidth

apps/prod/tekton/setup.yaml
=> fix(apps/prod/tekton): workaround for the k8s version support problem

apps/prod/tekton/setup.yaml, apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
=> fix(apps/prod/tekton): merge Kustomization `tekton-results-setup` into `tekton-setup`

apps/prod/tekton/setup.yaml, apps/prod/tekton/setup/triggers/interceptors.yaml, apps/prod/tekton/setup/triggers/release.yaml
Reverts PingCAP-QE/ee-ops#1103
=> Revert "fix(apps/prod/tekton): merge Kustomization `tekton-results-setup` into `tekton-setup`"

apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component.yaml
=> feat(apps/prod/tekton/configs/triggers/templates): add more annotations for recording

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
=> opt(apps/prod/tekton/configs/tasks): add env var `NPM_CONFIG_REGISTRY` to fast fetch npm packages

apps/prod/tekton/configs/tasks/pingcap-deliver-image.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml, apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
Auto sync the git content when it pushed on "main" branch.
=> feat(apps/prod/tekton/configs/triggers): auto sync content to ks3 bucket

apps/prod/tekton/configs/triggers/triggers/PingCAP-QE/artifacts/git-push.yaml
=> fix(apps/prod/tekton/configs/triggers): fix trigger `git-push-pingcap-qe-artifacts`

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
=> fix(apps/prod/tekton/configs/tasks): fix task `publish-tiup-from-oci-artifact`

apps/prod/tekton/configs/triggers/bindings/github-pr.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener-tibuild.yaml, apps/prod/tekton/configs/triggers/tests/dev-build.http, apps/prod/tekton/configs/triggers/tests/test-github-events.ts, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
=> feat(apps/prod/tekton/configs/triggers): support build with pr

apps/prod/tibuild/deployment.yaml
ref: https://github.com/PingCAP-QE/ee-apps/pull/138
=> fix(apps/prod/tibuild): bump tibuild

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
=> feat(apps/prod/tekton/configs/tasks): limit nightly tiup publish frequence

apps/prod/tekton/configs/tasks/pingcap-git-clone-ext.yaml
=> fix(apps/prod/tekton/configs/tasks): fix for pull request ref

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
=> feat(apps/prod/tekton/configs/tasks): add env var `RUSTUP_DIST_SERVER` in binary building step

apps/prod/tekton/configs/pvcs/cargo-home.yaml
> **How to revert**
> revert the pull request with some updates: keep the job and modify the command to make sure the `config` file will deleted.
=> feat(apps/prod/tekton/configs/pvcs): add global crate index mirror

apps/prod/tekton/configs/pvcs/cargo-home.yaml
Reverts PingCAP-QE/ee-ops#1144
=> Revert "Update cargo-home.yaml"

apps/prod/tibuild/deployment.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/139
/approve
=> feat(apps/prod/tibuild): bump tibuild version

apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml
=> fix(apps/prod/tekton/configs/triggers): add pod podAntiAffinity to be global lock

apps/prod/harbor/release.yaml
Reverts PingCAP-QE/ee-ops#1148
=> Revert "Update release.yaml"

apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml, apps/prod/tekton/configs/triggers/tests/test-github-events.ts
The errors were introduced by #1147
=> fix(apps/prod/tekton/configs/triggers/templates): fix pod template errors

apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml
=> fix(apps/prod/tekton/configs/triggers/templates): split the tiup global locks between staging and prod

apps/prod/tekton/configs/pipelines/pingcap-build-package-darwin.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
=> refactor(apps/prod/tekton/configs/tasks): only save nightly publications for prod tiup server

apps/prod/tekton/configs/tasks/hotfix/create-pr-to-sync-owners.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/_/git-create-branch.yaml
=> fix(apps/prod/tekton/configs): sync owners for tikv and pd's hotfix branches

apps/prod/tibuild/deployment.yaml
Ref https://github.com/PingCAP-QE/ee-apps/pull/143
=> fix(apps/prod/tibuild): bump to v20240228-52-g63d1681

apps/prod/tibuild/deployment.yaml
Reverts PingCAP-QE/ee-ops#1155
=> Revert "fix(apps/prod/tibuild): bump to v20240228-52-g63d1681"

apps/prod/tibuild/deployment.yaml
fix the frontend js error
/approve
=> fix(tibuild): bump to v20240228-53-g80bb966

apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
=> fix(apps/prod/tekton/configs/tasks): update task `create-pr-to-bump-tikv-version`

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
=> fix(apps/prod/tekton/configs/pipelines): increase timeout for step to wait tiup delivery

apps/prod/tekton/configs/pipelines/ko-build-prow.yaml, apps/prod/tekton/configs/pipelines/kustomization.yaml, apps/prod/tekton/configs/tasks/ko-prow.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml
=> refacgtor(apps/prod/tekton/configs): rename pipeline and task for new prow git repo

apps/gcp/prow/release/release.yaml
Reverts PingCAP-QE/ee-ops#1163
=> Revert "fix(apps/gcp/prow/release): bump hook to v20240614-fd27fb709"

apps/prod/harbor/release/release.yaml
=> fix(apps/prod/harbor/release): try to solve uploading issue with proxy service

apps/prod/tekton/configs/pipelines/kaniko-build.yaml, apps/prod/tekton/configs/pipelines/pull-pingcap-qe-artifacts-build-image.yaml, apps/prod/tekton/configs/tasks/pingcap-build-images.yaml
=> fix(apps/prod/tekton/configs/tasks): update image tag of kaniko executor image

apps/prod/tekton/configs/triggers/triggers/_/git-push-on-fips-branches.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
Reverts PingCAP-QE/ee-ops#1168
all mac machines is updated with new cmake version.
=> Revert "fix(apps/prod/tekton/configs/triggers): disable tiflash mac target builds"

apps/prod/tekton/configs/tasks/pingcap-git-clone-ext.yaml
___
Bug fix
___
- Fixed the condition in the `pingcap-git-clone-ext` task to correctly identify the "pingcap/tidb" repository by adding an additional check for "pingcap/tidb.git".
___
<tr>
<td>
<details>
<summary><strong>pingcap-git-clone-ext.yaml</strong><dd><code>Fix origin URL check in `pingcap-git-clone-ext` task</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/prod/tekton/configs/tasks/pingcap-git-clone-ext.yaml
<li>Updated the condition to check the origin URL for "pingcap/tidb".<br> <li> Added an additional check for "pingcap/tidb.git".<br>
</details>
</td>
<td><a …
=> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-git-clone-ext`

apps/prod/tekton/configs/triggers/tests/test-github-events.ts, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-push.yaml
___
Bug fix, Enhancement
___
- Added error handling for non-OK responses in the `getCommitSha` function in `test-github-events.ts`.
- Simplified and consolidated CEL filters in `git-push.yaml` by combining repository and branch filters.
___
<tr>
<td>
<details>
<summary><strong>test-github-events.ts</strong><dd><code>Add error handling for fetch response in test script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/prod/tekton/configs/triggers/tests/test-github-events.ts
<li>Added error handling for non-OK responses in <code>getCommitSha</code> function.<br>
</details>
</td>
<td><a …
=> chore(apps/prod/tekton/configs/triggers): fix trigger test script

apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflow/git-push.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push.yaml
___
Bug fix
___
- Increased timeout values for several repositories in various Tekton trigger configurations.
- Updated timeout values from 30m to 40m for repositories including `pingcap/tidb`, `pingcap/tiflow`, and `tikv/pd`.
___
<tr>
<td>
<details>
<summary><strong>fake-github-branch-push.yaml</strong><dd><code>Increase timeout values for branch push triggers</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml
- Increased timeout values for several repositories.
</details>
</td>
<td><a …
=> fix(apps/prod/tekton/configs/triggers): increase timeout for serval repos

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
___
Enhancement
___
- Added a new `wait-image-delivery` task in the GA release flow to check image delivery.
- Simplified the `wait-tiup-delivery` task by removing unnecessary parameters and installation steps.
- Updated parameter names for consistency across tasks.
- Limited pull concurrency to 1 in the `publish-tiup-from-oci-artifact` task to reduce read failure.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pingcap-release-ga.yaml</strong><dd><code>Add image delivery check task and simplify existing tasks</code></dd></summary>
<hr>
apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
<li>Added a new task …
=> chore(apps/prod/tekton/configs/pipelines): add fake wait image delivery task in ga release flow

apps/prod/dl/release.yaml
=> fix(apps/prod/dl): fix sa for dl pod

apps/prod/kafka/kustomization.yaml, apps/prod/kafka/namespace.yaml, apps/prod/kafka/operator-release.yaml, apps/prod/kustomization.yaml, infrastructure/_base/sources/helm-repo-others.yaml
implement with https://strimzi.io/
=> feat(apps/prod): add kafka operator

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml
=> fix(apps/prod/tekton/configs/tasks): use the mirror registry to download oci files

apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact.yaml
Reverts PingCAP-QE/ee-ops#1191
=> Revert "fix(apps/prod/tekton/configs/tasks): use the mirror registry to download oci files"

apps/prod/jenkins-beta/release/release.yaml, apps/prod/jenkins-beta/release/values-JCasC.yaml, apps/prod/jenkins-beta/release/values-agent.yaml, apps/prod/jenkins-beta/release/values-controller-plugins.yaml, apps/prod/jenkins-beta/release/values-controller.yaml, apps/prod/jenkins-beta/release/values-persistence.yaml, infrastructure/_base/sources/helm-repo-others.yaml
=> fix(apps/prod/jenkins-beta): upgrade chart

apps/prod/jenkins-beta/release/release.yaml, apps/prod/jenkins-beta/release/values-controller-plugins.yaml, apps/prod/jenkins-beta/release/values-controller.yaml
=> fix(jenkins/release/jenkins-beta): upgrade jenkins to v2.440.3

apps/prod/jenkins-beta/release/release.yaml
=> fix(jenkins/release/jenkins-beta): upgrade jenkins to v2.452.3

apps/prod/jenkins/release/release.yaml, apps/prod/jenkins/release/values-JCasC.yaml, apps/prod/jenkins/release/values-controller-plugins.yaml, apps/prod/jenkins/release/values-controller.yaml
=> fix(jenkins/release/jenkins): update jenkins to 2.452.3-jdk17

apps/prod/jenkins-beta/release/values-controller-plugins.yaml
=> fix(apps/prod/jenkins-beta): overwrite plugins with list in GitOps

apps/prod/jenkins/post/kustomization.yaml, apps/prod/jenkins/post/tiflash/kustomization.yaml, apps/prod/jenkins/post/tiflash/namespace.yaml, apps/prod/jenkins/post/tikv/kustomization.yaml, apps/prod/jenkins/post/tikv/namespace.yaml
=> fix(apps/prod/jenkins/post): add jenkins-tikv and jenkins-tiflash namespaces

apps/prod/kafka/clusters/cd/cluster.yaml, apps/prod/kafka/clusters/cd/topics.yaml, apps/prod/kafka/clusters/kustomization.yaml
=> feat(apps/prod/kafka): add cluster and topics

apps/prod/tekton/configs/triggers/event-listeners/event-listener-internal.yaml, apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/_/harbor/artifact-push-on-harbor.yaml, apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
=> chore(apps/prod/tekton/configs/triggers): limit harbor push event resource url

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml
=> chore(apps/prod/tekton/configs): increase timeout for tiup publish

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-create-tag.yaml
=> fix(pingcap/tidb-operator): support wide version tag

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/release/pingcap-create-github-releases.yaml
=> feat(apps/prod/tekton/configs): add task in GA release flow to create github releases

apps/prod/coder/kustomization.yaml, apps/prod/coder/release.yaml, apps/prod/coder/release/kustomization.yaml, apps/prod/coder/release/namespace.yaml, apps/prod/coder/release/release.yaml, apps/prod/coder/release/source.yaml, apps/prod/kustomization.yaml
=> feat(apps/prod/coder): add experiment

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml
=> fix(apps/prod/tekton/configs/tasks): try to address  increase `max_old_space_size`

apps/prod/tekton/configs/triggers/triggers/_/harbor/image-push-on-harbor.yaml
Reverts PingCAP-QE/ee-ops#1264
=> Revert "chore(apps/prod/tekton/configs/triggers): tmp disable sync for lt v8.x images"

apps/prod/tiup-publisher/release-prod-mirror.yaml, apps/prod/tiup-publisher/release-staging-mirror.yaml
=> chore(apps/prod/tiup-publisher): bump docker image to `v20240228-86-gc1947d9`

apps/prod/tekton/configs/tasks/ci/ci-helper-for-pr.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/triggers/bindings/github-pr.yaml, apps/prod/tekton/configs/triggers/event-listeners/event-listener-public.yaml, apps/prod/tekton/configs/triggers/templates/_/ci-helper-for-pr.yaml, apps/prod/tekton/configs/triggers/templates/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/_/github-pr-labeled.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
=> feat(apps/prod/tekton/configs): add new flow to help ci on PRs

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml
=> chore(apps/prod/publisher): bump docker image version to `v2024.10.14-3-ged099a3`

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml
=> chore(apps/prod/publisher): bump  publisher version to v2024.10.14-4-ga7470b6

apps/prod/prow-worker/pvc.yaml
Add pvc for cargo-home cache in namespace prow-test-pods.
=> feat(prow-worker): add pvc for cargo-home cache

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-operator/git-push.yaml
from 15 minutes to 30 minutes.
=> fix(pingcap/tidb-operator): increase timeout for build jobs

apps/prod/tekton/configs/triggers/templates/_/push-oci-artifact-to-tiup.yaml, apps/prod/tekton/configs/triggers/triggers/_/harbor/artifact-push-on-harbor.yaml
=> feat(apps/prod/tekton/configs/triggers): fix tiup and fs triggers

apps/gcp/prow/release/release.yaml
=> opt(apps/gcp/prow/release): try to fastup tide update speed

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml
=> chore(deps): bump image ghcr.io/pingcap-qe/ee-apps/publisher to `v2024.11.4-10-g93bf843`

apps/prod/tekton/configs/tasks/pingcap-deliver-image.yaml, apps/prod/tekton/configs/tasks/release/pingcap-create-github-releases.yaml
add step in task `pingcap-create-github-releases`.
=> feat(apps/prod/tekton/configs/tasks/release): add branch creating step

apps/prod/coder/release/release.yaml
=> chore(deps): bump coder to 2.16.1

apps/prod/tekton/configs/triggers/tests/test-github-events.ts
Changes:
- we need to pass the `--token` option to provide the GitHub private token to solve the api rate limit.
=> fix(apps/prod/tekton/configs/triggers/tests): solve the api rate limit of GitHub

apps/prod/jenkins-beta/release/values-controller.yaml
=> fix(apps/prod/jenkins-beta/release): bump jenkins version to 2.462.3

apps/prod/jenkins/release/values-JCasC.yaml
Reverts PingCAP-QE/ee-ops#1353
=> Revert "chore(prod/jenkins): add secret for ks3util config"

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml, apps/prod/tekton/configs/tasks/publish-fileserver-from-oci-artifact.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml
=> chore(deps): bump publisher image tag to v2024.11.4-16-g8c2a836

apps/prod/coder/release/release.yaml
=> chore(deps): bump coder to 2.18.0

apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin-v2.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries-darwin.yaml, apps/prod/tekton/configs/tasks/pingcap-build-binaries.yaml, apps/prod/tekton/configs/triggers/tests/test-github-events.ts
=> fix(apps/prod/tekton/configs/tasks): revert rustup mirrors

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml, apps/prod/tekton/configs/tasks/publish-fileserver-from-oci-artifact.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml
=> chore(apps/prod): bump image ghcr.io/pingcap-qe/ee-apps/publisher version to v2024.12.12-2-g492a0b1

apps/gcp/prow/release/release.yaml
Reverts PingCAP-QE/ee-ops#1383
=> Revert "fix(apps/gcp/prow/release): fix jenkins url link pr context"

apps/gcp/prow/release/release.yaml
=> chore(apps/gcp/prow/release): debug jenkins url link pr context with upstream version

apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-branch-push.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-pr.yaml, apps/prod/tekton/configs/triggers/triggers/_/fake-github/fake-github-tag-create.yaml
=> fix(apps/prod/tekton/configs/triggers/triggers/_/fake-github): support for tidb-dashboard

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/release/tag-rc2ga-on-oci-artifacts.yaml, apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml, apps/prod/tekton/configs/tasks/release/wait-delivery-tiup.yaml
=> refactor(apps/prod/tekton/configs/pipelines): extract inner task spec to a separate tasks in ga relase pipeline

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml
=> fix(apps/prod/tekton/configs): fix task refs for pipeline `pingcap-release-ga`

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml, apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml, apps/prod/tekton/configs/tasks/release/wait-delivery-tiup.yaml
Changes makes:
- implement task `wait-delivery-images`
- update the pipeline `pingcap-release-ga`
=> feat(apps/prod/tekton/configs): implement step to wait for image delivery

apps/prod/tekton/configs/tasks/kustomization.yaml, apps/prod/tekton/configs/tasks/release/pingcap-create-github-alpha-tags.yaml
The script will be implemented in the future.
=> feat(apps/prod/tekton/configs/tasks/release): add task pingcap-create-github-alpha-tags

apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
=> fix(apps/prod/tekton/configs/tasks/release): add ref issue for tikv bump task

apps/prod/tekton/configs/tasks/hotfix/create-pr-to-sync-owners.yaml
=> feat(ticdc): add new cdc repo for owners file syncing

apps/gcp/prow/release/release.yaml
=> feat(pingcap/ticdc): add sticky lgtm for ticdc repo

apps/prod/tekton/configs/tasks/release/pingcap-create-github-alpha-tags.yaml
=> feat(apps/prod/tekton/configs/tasks/release): add step to reset tiup rate limit after tag created

apps/prod/publisher/release-prod-mirror.yaml, apps/prod/publisher/release-staging-mirror.yaml, apps/prod/tekton/configs/pr_body.txt, apps/prod/tekton/configs/tasks/publish-fileserver-from-oci-artifact.yaml, apps/prod/tekton/configs/tasks/publish-tiup-from-oci-artifact-v2.yaml, apps/prod/tekton/configs/tasks/release/pingcap-create-github-alpha-tags.yaml
=> chore(apps/prod): bump publisher version to v2024.12.12-6-g069f4f2

apps/prod/tibuild/deployment.yaml
Ref https://github.com/PingCAP-QE/ee-apps/pull/219
=> chore(apps/prod/tibuild): bump image tag to `v2024.12.12-7-g7b83308`

apps/_crds/prow/kustomization.yaml
=> fix(apps/_crds/prow): apply prow crd from ti-community-infra/prow repo

apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml, apps/prod/tekton/configs/tasks/pingcap-upload-offline-package.yaml
remove the `yum install` step, the new image is based on alpine.
=> fix(apps/prod/tekton/configs/tasks): fix upload tasks

apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push.yaml
Ref https://github.com/PingCAP-QE/artifacts/issues/554
=> feat(apps/prod/tekton/configs/triggers): add building trigger for tiflash failpoint edition

apps/prod/tibuild/deployment.yaml
Devbuild support newarch ticdc, ref https://github.com/PingCAP-QE/ee-apps/pull/232
=> feat(apps/proc/devbuild): devbuild support newarch ticdc

apps/prod/tekton/configs/tasks/release/wait-delivery-images.yaml
in GA image wait delivery task.
=> chore(apps/prod/tekton/configs/tasks): update output message

apps/prod/tibuild/deployment.yaml
Ref https://github.com/PingCAP-QE/ee-apps/pull/233
=> fix(apps/prod/tibuild): bump image tag to `v2025.1.30-6-gffafe99`

apps/prod/chatops-lark/release.yaml
Ref: https://github.com/PingCAP-QE/ee-apps/pull/236
=> chore(apps/prod/chatops-lark): bump chat release to 0.1.1

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version-v2.yaml
=> fix(apps/prod/tekton/configs/tasks): fix task pingcap-get-set-release-version-v2

apps/prod/tekton/configs/tasks/release/create-pr-to-bump-tikv-version.yaml
- Update task: `create-pr-to-bump-tikv-version`.
=> feat(apps/prod/tekton/configs/tasks/release): update task to support new release strategy

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
=> fix(apps/prod/tekton/configs/triggers): fix overlays for ctl build triggers

apps/prod/tekton/configs/triggers/triggers/pingcap/tidb-dashboard/git-push.yaml
- add support for release-X.Y-beta.M branches.
=> fix(apps/prod/tekton/configs/triggers): fix for tidb-dashboard

apps/prod/tekton/configs/triggers/triggers/_/ctl/artifact-push-on-harbor.yaml
Extract architecture from last tag element and use single git ref value
=> refactor(apps/prod/tekton/configs/triggers): simplify artifact tag parsing in Harbor triggers for ctl pkg

apps/prod/tekton/configs/tasks/pingcap-upload-enterprise-plugins.yaml
Add additional sed pattern to also handle .pre suffix in enterprise plugin filenames when uploading to S3.
=> fix(apps/prod/tekton/configs/tasks): fix task `pingcap-upload-enterprise-plugins`

apps/prod/tibuild/deployment.yaml
ref: https://github.com/PingCAP-QE/ee-apps/compare/ffafe99...v2025.4.8
=> chore(apps/prod/tibuild): update tibuild image to v2025.4.8

apps/prod/chatops-lark/release.yaml
Ref:
- https://github.com/PingCAP-QE/ee-apps/pull/254
- https://github.com/PingCAP-QE/ee-apps/pull/256
=> chore(apps/prod/chatops-lark): bump image tag to v2025.4.8-2-gb009fdc

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap-inc/tici/git-create-tag.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap-inc/tici/git-push.yaml
- Create trigger configurations for pingcap-inc/tici repository
- Add git-push.yaml to build master branch with linux targets
- Add git-create-tag.yaml to build tagged versions
- Update kustomization.yaml to include new trigger files
Issue: close #1476
=> feat(tekton): add build support for tici component

apps/prod/chatops-lark/release.yaml
update chatops lark image.
relate to https://github.com/PingCAP-QE/ee-apps/pull/262
=> feat(chatops-lark): update chatops lark image

apps/prod/tibuild/deployment.yaml
ref: https://github.com/pingcap-qe/ee-apps/commit/d5e9871
=> chore(apps/prod/tibuild): bump image to v2025.4.8-9-gd5e9871

apps/prod/tekton/configs/pr_body.txt, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/tidbcloud/cloud-storage-engine/git-push-branch-build.yaml, apps/prod/tekton/configs/triggers/triggers/tidbcloud/tiflash-cse/git-push-branch-build.yaml
update enterprise to next-gen for tiflash-cse and cloud-storage-engine repo
=> fix(apps/prod/tekton/configs/triggers): Update build profiles

apps/prod/tekton/configs/triggers/triggers/tidbcloud/cloud-storage-engine/git-push-branch-build.yaml
=> fix(apps/prod/tekton/configs/triggers): remove cloud-engine from ch build trigger

apps/prod/tekton/configs/tasks/pingcap-get-set-release-version-v2.yaml
Add support for CSE version format and delete date style tags
=> feat(apps/prod/tekton/configs/tasks): update task 'pingcap-get-set-release-version-v2'

apps/prod/tibuild/deployment.yaml
Ref PingCAP-QE/ee-apps@2be9e34
=> feat(apps/prod/tibuild): bump image to v2025.4.8-19-g2be9e34

apps/prod/chatops-lark/release.yaml, apps/prod/tibuild/deployment.yaml
Ref PingCAP-QE/ee-apps@41dbc83
=> chore(apps/prod): update chatops-lark and tibuild image versions

apps/prod/chatops-lark/release.yaml
Ref PingCAP-QE/ee-apps@290803f
=> chore(apps/prod/chatops-lark): update release.yaml

apps/prod/cloudevents-server/release.yaml
Ref: PingCAP-QE/ee-apps@3ca16d7
=> chore(apps/prod/cloudevents-server): bump image tag to v2025.4.8-25-g3ca16d7

apps/gcp/prow/release/release.yaml
Ref ti-community-infra/prow@3d7188248
=> fix(apps/gcp/prow): bump hook image tag to v20250515-3d7188248

apps/prod/tibuild/deployment.yaml
Ref PingCAP-QE/ee-apps@d38ba90
=> feat(apps/prod/tibuild): bump image tag to v2025.4.8-27-gd38ba90

apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tidb/git-push-branch-build.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push-branch-build.yaml, apps/prod/tekton/configs/triggers/triggers/tikv/pd/git-push-branch-build.yaml
Close PingCAP-QE/ci#3536
Close PingCAP-QE/ci#3543
- Add triggers for pingcap/tidb, pingcap/tiflash, and tikv/pd branch builds
- Update kustomization.yaml to reference new trigger files
- Rename and update trigger files for consistency and next-gen support
=> feat(apps/prod/tekton/configs/triggers): add and update triggers for next-gen branch builds

apps/prod/tekton/configs/triggers/triggers/pingcap/tiflash/git-push-branch-build.yaml
=> chore(apps/prod/tekton/configs/triggers): expand branch patterns for tiflash next-gen target

apps/prod/tekton/configs/pipelines/pingcap-release-ga.yaml
refactor pipeline: pingcap-release-ga
=> refactor(apps/prod/tekton/configs/pipelines): rename pre-version parameter to rc-version 

apps/prod2/kustomization.yaml
The OpenEBS infrastructure is ready, so let's enable coder.
=> chore(apps/prod2): enable coder resource in prod2 kustomization

infrastructure/prod2/nfs-pvc-provisioner/deployment.yaml, infrastructure/prod2/nfs-pvc-provisioner/kustomization.yaml, infrastructure/prod2/nfs-pvc-provisioner/pvc.yaml, infrastructure/prod2/nfs-pvc-provisioner/release-csi-nfs.yaml, infrastructure/prod2/nfs-pvc-provisioner/source-csi-nfs.yaml, infrastructure/prod2/nfs-pvc-provisioner/svc.yaml
- Add deployment and service for NFS server 
- Update PVC and HelmRelease to use CSI driver NFS 
- Add HelmRepository for CSI driver NFS 
- Update kustomization resources accordingly 
- Rename release.yaml to release-csi-nfs.yaml
=> refactor(prod2): add NFS server deployment and migrate to CSI driver NFS

apps/gcp/tekton/configs.yaml, apps/gcp/tekton/setup.yaml, apps/gcp/tekton/setup/kustomization.yaml, apps/gcp/tekton/setup/operator-config.yaml
- Switch operator release source and version
- Update pipeline and trigger settings for stability and metrics
- Remove unused image and secret substitution in setup
- Add nodeSelector to operator config
=> fix(apps/gcp/tekton): update Tekton operator to v0.76.0 and revise configs

apps/gcp/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml, apps/gcp/tekton/configs/triggers/templates/_/build-component-single-platform.yaml, apps/gcp/tekton/configs/triggers/templates/_/build-component.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component-all-platforms.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component-single-platform.yaml, apps/prod/tekton/configs/triggers/templates/_/build-component.yaml, apps/prod/tekton/configs/triggers/templates/_/ctl/build-component-single-platform.yaml
Reverts PingCAP-QE/ee-ops#1585
=> Revert "refactor(apps/prod, apps/gcp): update Tekton templates to use tasks timeout param"

apps/gcp/prow/release/release.yaml
Ref the prow changes: [ti-community-infra/prow@57374e9...f07f5145d](https://github.com/ti-community-infra/prow/compare/57374e9...f07f5145d)
=> chore(deps): update Tide and Hook images tag to `v20250903-f07f5145d`

apps/prod/jenkins/release/values-JCasC.yaml
Close https://github.com/PingCAP-QE/ee-ops/issues/1484
* Add two credentials for docs-cn.
* Add Feishu webhook credentials for daily notifications.
=> config(prod/jenkins): add two credentials for docs-cn

apps/gcp/tekton/configs/triggers/triggers/kustomization.yaml, apps/gcp/tekton/configs/triggers/triggers/pingcap/ticdc/git-push-branch-build.yaml, apps/prod/tekton/configs/triggers/triggers/kustomization.yaml, apps/prod/tekton/configs/triggers/triggers/pingcap/ticdc/git-push-branch-build.yaml
=> feat(apps/gcp/tekton,apps/prod/tekton): add ticdc branch build triggers
